### ISSUE TITLE
Make MDX2JSON web app as a parameter

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#108]
Now /MDX2JSON is hardcoded. Make it configurable from some config.json in /dsw folder

**Comment by gnibeda** [comment]
Introduced `config.json` support in `configs` folder. Structure:
```json
{
    "endpoints": {
        "mdx2json": "mdx2json"
    }
}
```

**Comment by eduard93** [comment]
@TsvetkovAV maybe move tileserver here?

**Comment by evshvarov** [comment]
I think it is OK as a application-wide parameter. I doubt that there would
be cases with different tile servers on same ISC server.
But even if it would you can setup different DSW apps with different
/MDX2JSON and/or TILE servers
чт, 22 марта 2018 г. в 13:44, Aleksandr <notifications@github.com>:
