### ISSUE TITLE
Don't reset the legend If you change the value of filter

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#140]
If you change it now it turns on some rows in legend back

**Comment by gnibeda** [comment]
Please provide an example. Because I can't reproduce it. Need to now the exact chart type and data.

**Comment by Lena-Ev** [comment]
@evshvarov example please

**Comment by evshvarov** [comment]
Here is an [example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Widget%20Examples/Linked%20Widgets.dashboard)

**Comment by Lena-Ev** [comment]
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/user/Widget%20Examples/Linked%20Widgets.dashboard

**Comment by gnibeda** [comment]
Done in 3.1.87
