### ISSUE TITLE
Migration to TS and Angular 10

### ISSUE THREAD

**Issue by gnibeda** [intersystems-community/DeepSeeWeb#150]
This is global topic for issues with v3, after migration to TypeScript and Angular 10.
Please post all issues related to this version here.

**Comment by gnibeda** [comment]
There are incorrect colors for bubble chart:
![bf0386b8-e376-48f4-ae6a-f0d22442ca35](https://user-images.githubusercontent.com/9804674/89904210-4f2a6080-dbf1-11ea-822e-2eba45ddbd60.jpg)

**Comment by gnibeda** [comment]
broken redirect "from" for login page

**Comment by gnibeda** [comment]
no export to xls/csv

**Comment by evshvarov** [comment]
No "View as another chart type" menu

**Comment by evshvarov** [comment]
Widget menu doesn't work in Expanded mode

**Comment by evshvarov** [comment]
Make sizes "Free", but not tied to the monitor screen

**Comment by evshvarov** [comment]
Need to supply the namespace to login page: it is impossible now to have it filled in the Namespace field
