### ISSUE TITLE
DSW 3 doesn't obey color categories in charts

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#154]
See the examples:
dsw 2.1.51
<img width="1181" alt="Screenshot 2020-08-26 at 23 32 21" src="https://user-images.githubusercontent.com/2781759/91353890-90775e80-e7f4-11ea-9805-6766c20316f7.png">
dsw 3.0.5
<img width="1187" alt="Screenshot 2020-08-26 at 23 33 50" src="https://user-images.githubusercontent.com/2781759/91353933-9bca8a00-e7f4-11ea-89b1-5988fc9ea16f.png">

**Comment by gnibeda** [comment]
done in 3.0.7a
