### ISSUE TITLE
add the option to cancel connection of any widget to a tile

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#163]
<img width="515" alt="Screenshot 2020-12-11 at 18 15 26" src="https://user-images.githubusercontent.com/2781759/101920569-04d7e100-3bdd-11eb-86df-0e0ac9979650.png">

**Comment by evshvarov** [comment]
Now if you assigned the widget you cannot cancel it later

**Comment by Lena-Ev** [comment]
Now you can choose empty space to remove the widget
<img width="372" alt="image" src="https://user-images.githubusercontent.com/77621970/213662717-77ab3aab-47b0-4038-b986-61bba0e1e3f3.png">
