### ISSUE TITLE
horizontalControls / verticalControls widgets support

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#168]
horizontalControls / verticalControls widgets are just groupings for controls. 

Currently getting this error: `Widget is not supported: horizontalControls`

![image](https://user-images.githubusercontent.com/5127457/107694707-bf10c500-6cc0-11eb-8321-bbe6906d5a23.png)

Please add support for them (draw filters).

**Comment by eduard93** [comment]
Any news on that?

**Comment by gnibeda** [comment]
fixed in 3.1.4
