### ISSUE TITLE
Custom Widgets

### ISSUE THREAD

**Issue by qou99** [intersystems-community/DeepSeeWeb#170]
The links in the readme do not work for this. Can you tell me how to create and use custom widgets?

**Comment by gnibeda** [comment]
link fixed

**Comment by qou99** [comment]
Thank you @gnibeda for the quick reply. But I didn't get that to work. Maybe you can help once again.

For testing I used the simple-addon.component example. After building, i have received 2 files:
addon-0-es5.aa72bf39663443001315.js
addon-0-es2015.aa72bf39663443001315.js

I renamed one file and put it in the directory ..\CSP\dsw\addons\CustomWidgetTest.js
![1](https://user-images.githubusercontent.com/37990393/109201519-3b67d580-77a2-11eb-99f2-d238d024fa55.jpg)

The class DSW.Addons.CustomWidgetTest was created and I added it to a dashborard. Unfortunately DSW says "not supported".
When reloading the page I get an error.
![4](https://user-images.githubusercontent.com/37990393/109204095-39ebdc80-77a5-11eb-9bb9-33022e2464d5.jpg)

I would be grateful if you could take a look at this.

**Comment by evshvarov** [comment]
could you make it all in lowercase? I think it is case-sensitive. I had problems with that previously

**Comment by qou99** [comment]
I tried that, but unfortunately it didn't changed anything.

**Comment by evshvarov** [comment]
Do you have a test repo? could you please share it?

**Comment by gnibeda** [comment]
File should be named as protlet, so `DSW.Addons.CustomWidgetTest.js`
But anyway, can you provide link to your js file, or drop it in support telegram channel?
I'll check what's going wrong.

**Comment by qou99** [comment]
Here is the link to the files: https://github.com/qou99/dsw
I have not made any changes to the example class.

**Comment by gnibeda** [comment]
Seems there are issues with Angular CLI. There is no needed metadata in prod build, so we need do build addons without `--prod` flag.
Can you run `npm run build:addons` command to build addon and check it again?

_Documentation has been upated_

**Comment by qou99** [comment]
Now 4 files were created. Uploaded here https://github.com/qou99/dsw
addon-0-es5.js
addon-0-es5.js.map
addon-0-es2015.js
addon-0-es2015.js.map

I also get an error message:
![1](https://user-images.githubusercontent.com/37990393/109273151-1ad76400-7812-11eb-85dd-0398f3132d46.jpg)
![2](https://user-images.githubusercontent.com/37990393/109273161-1e6aeb00-7812-11eb-8876-e4547d883fe2.jpg)

If I name the file DSW.Addons.CustomWidgetTest.js, DSW creates the class DSW.Addons.DSW.Addons.CustomWidgetTest. Doesn't feel right.

If I omit the map file, I also get an error:
_DevTools failed to load SourceMap: Could not load content for http://192.168.21.76:52774/dsw/addons/addon-0-es5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE_

**Comment by gnibeda** [comment]
Finally figure out real issue. In current implementation addons can't be loaded into different DSW build. This means that if you use already built DSW and addon that you build yourself - it won't work.
Temporary solution is:
1. Build DSW yourself: `npm run build`
2. Deploy this version to your website. `/dist`  - folder with compiled DSW
3. Build your addon: `npm run build:addons`
4. Deploy addon

However, with Angular 11 there is new way of addons loading.
Currently I'm working on it, and hope that new implementation can solve this issue.
You can just wait and I'll write results here when I'm done.

**Comment by gnibeda** [comment]
Tried Angular11 + webpack5 module federation, but not usable in our case due to a lot of external libs. Also webpack5 support is experimental and no reccomended for production.
So I've developed new approach for external component loading.
Documentation has been updated and now contains all detailed information: https://github.com/intersystems-community/DeepSeeWeb/blob/master/Addons.md

Please make pull from repo and use new addon example. Also please read new documentation

**Comment by qou99** [comment]
Thank you for your quick response. Unfortunately, I still can't get it running.
I'm trying to get one of the examples, like Html Viewer, to work.

DSW cannot create the class because there is a "-" in the name, so I renamed the files as follows:
![1](https://user-images.githubusercontent.com/37990393/109648799-55673680-7b5b-11eb-9dcd-d363ae5581c6.jpg)
![2](https://user-images.githubusercontent.com/37990393/109648813-59935400-7b5b-11eb-92ae-567fe364e91b.jpg)

Classes were generated:
![3](https://user-images.githubusercontent.com/37990393/109648843-631cbc00-7b5b-11eb-8dfe-de08908f763d.jpg)

I have created a dashboard and called it in DSW. Get the following error:
![4](https://user-images.githubusercontent.com/37990393/109648864-6ca62400-7b5b-11eb-9d09-25a6c6e93b15.jpg)
![5](https://user-images.githubusercontent.com/37990393/109648884-7039ab00-7b5b-11eb-93e3-ff128653a226.jpg)

Have I missed something?
![6](https://user-images.githubusercontent.com/37990393/109648944-847da800-7b5b-11eb-8a9e-f1992082d472.jpg)

**Comment by gnibeda** [comment]
Can you host you DSW somewhere, so I can take a look?
This error from previous version of DSW and this is strange. Need to check your case to figure out what happens.

**Comment by gnibeda** [comment]
Can you try this file?
[html-viewer.component.zip](https://github.com/intersystems-community/DeepSeeWeb/files/6068972/html-viewer.component.zip)

**Comment by qou99** [comment]
With the new file I get the same error.

I have created an InterSystems Learning Lab Instance and installed ZPM and DSW (USER NS).
The Problem can be reproduced here.

DSW: https://52773-1-a37b0e6b.labs.learning.intersystems.com/dsw/index.html

IDE: 3000-0-a37b0e6b.labs.learning.intersystems.com/#/home/project
InterSystems IRIS Username: tech
InterSystems IRIS Password: demo
Management Portal: 52773-1-a37b0e6b.labs.learning.intersystems.com/csp/sys/UtilHome.csp
IDE Connections (including VSCode and Atelier)
Host Server Address: 52773-1-a37b0e6b.labs.learning.intersystems.com
Host Server Web Port: 80
External Connections (including InterSystems Studio)
InterSystems IP: 34.67.32.63
InterSystems 51773 Port: 22355
InterSystems 1972 Port: 25134

**Comment by gnibeda** [comment]
Looks like it caused by Angular's buildOptimizer. I've temporary disabled it in 3.1.2.
Please deploy this version on this instance.

**Comment by qou99** [comment]
now "not supported" is displayed

**Comment by gnibeda** [comment]
I've checked provided link with demo, seems html widget works. Do you have any issues with it?

**Comment by qou99** [comment]
No more Problems. Works fine now. Thank you.
There is only one more thing i noticed: If i delete the DSW Package via Studio, all files in the /CSP/dsw directory are also deleted. DSW must then be reinstalled.
