### ISSUE TITLE
if you click on '0' in widget settings spoils the axis legend

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#171]
Click on 0 in settings on any graph widget and axis labels disappear:
<img width="503" alt="Screenshot 2021-03-01 at 19 38 08" src="https://user-images.githubusercontent.com/2781759/109528385-a9bfd700-7ac5-11eb-82b6-d5950281e297.png">

**Comment by gnibeda** [comment]
fixed in 3.1.4
