### ISSUE TITLE
Logout doesn’t work

### ISSUE THREAD

**Issue by qou99** [intersystems-community/DeepSeeWeb#175]
Logout doesn’t work. The CSP Session is not terminated.

**Comment by eduard93** [comment]
What security settings are you using for web app? And what's security level for a system?

**Comment by qou99** [comment]
IRIS Security Setting is normal (not minimal or lockeddown).
Web App /dsw is unauthenticated.
Web App /MDX2JSON is unauthenticated/password.

**Comment by eduard93** [comment]
Set password only for `/MDX2JSON`

**Comment by qou99** [comment]
If I set it to password only, the following problems arise (Role %All assigned for testing)

- Addons cannot be loaded
![addons](https://user-images.githubusercontent.com/37990393/110348375-de85de00-8031-11eb-8d5d-32c7fc9db18a.jpg)

- Login on remote Systems does not work (localhost works)

https://user-images.githubusercontent.com/37990393/110348451-f5c4cb80-8031-11eb-844a-5e3f95e1547b.mov

**Comment by evshvarov** [comment]
Add MatchRoles for /MDX2JSON
e.g
set webProperties("MatchRoles")=":%DB_IRISAPP"
  like here.
<https://github.com/evshvarov/covid-19/blob/1237687886a5cc1386412d3034092f81563699d4/src/Covid19/Utils.cls#L192>

**Comment by qou99** [comment]
I reseted everything, tried again and now it works. I don't know exactly where the problem was. If I find out more I will post it here. Please close for now.
