### ISSUE TITLE
GeoJSON support

### ISSUE THREAD

**Issue by LudmilaValerko** [intersystems-community/DeepSeeWeb#178]
we need GeoJSON support in DeepSeeWeb to build analytical maps.

**Comment by evshvarov** [comment]
If you provide a dashboard with GeoJSON it'd be easier to develop the
support.

**Comment by LudmilaValerko** [comment]
Example:
Dashboard
http://161.97.80.143:52777/dsw/index.html#/MAP/map/Map.dashboard

Polygones:
http://161.97.80.143:52777/csp/map/UAMap.geojson
http://161.97.80.143:52777/csp/map/UAMap.json

**Comment by evshvarov** [comment]
Done in 3.1.16.
Need a public example. @LudmilaValerko, could you please provide any?

**Comment by LudmilaValerko** [comment]
> Done in 3.1.16.
> Need a public example. @LudmilaValerko, could you please provide any?

Yes, we will prepare an example.

**Comment by eduard93** [comment]
@evshvarov @MakarovS96 Public example https://github.com/intersystems-community/dsw-map/pull/6
