### ISSUE TITLE
Dosn`t display chosen value in filter field

### ISSUE THREAD

**Issue by LudmilaValerko** [intersystems-community/DeepSeeWeb#182]
In DSW dashboard we can`t see the chosen value for Filter
![01](https://user-images.githubusercontent.com/56110908/123433014-ad76ec80-d5d3-11eb-8b72-76e10025d11b.PNG)

![02](https://user-images.githubusercontent.com/56110908/123433030-b2d43700-d5d3-11eb-86b3-3cda224672bb.PNG)

**Comment by gnibeda** [comment]
done in 3.1.14
