### ISSUE TITLE
Colcharts (and other graph widgets) do not respect number formatting

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#185]
It doesn't respect or initial(system settings) formatting from pivot source nor special formatting in pivot or in a widget.
E.g. here we should see comma separator for thousands:
![telegram-cloud-photo-size-2-5438112270086419379-y](https://user-images.githubusercontent.com/2781759/125654701-1a318d15-ae90-4e26-b18b-6f95189275f9.jpg)

**Comment by gnibeda** [comment]
fixed in 3.1.16
