### ISSUE TITLE
add "show value" setting for pie charts

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#186]
Turned on by default.
If turned of and with turned on annotations it shows both annotation and value, as it is shown here:
Windows is annotation, 2,200 is a value.
<img width="356" alt="Screenshot 2021-07-14 at 19 07 26" src="https://user-images.githubusercontent.com/2781759/125655768-3cac7cd8-67cf-45be-9fb5-19e484d9c292.png">

**Comment by gnibeda** [comment]
fixed in 3.1.16

**Comment by evshvarov** [comment]
Sometimes it can be set in this state :)
<img width="349" alt="Screenshot 2021-08-18 at 09 06 10" src="https://user-images.githubusercontent.com/2781759/129846308-a86d0f36-6917-4a01-98f0-ee9436dbd1a7.png">
