### ISSUE TITLE
add "show percentage" setting for pie-charts

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#187]
sign -"%"
turned off by default.
if turned on it shows % of the value of total in the annotation. Example:
<img width="356" alt="Screenshot 2021-07-14 at 19 07 26" src="https://user-images.githubusercontent.com/2781759/125656130-05196703-1c7a-4a5c-8f2d-f58696e50768.png">
If it will be turned on it should show Windows, 2,200, 64%
Or only Windows, 64% if the value option is off

**Comment by gnibeda** [comment]
fixed in 3.1.16

**Comment by evshvarov** [comment]
done in 3.1.22
