### ISSUE TITLE
Add loading indicator for maps 

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#191]
while waiting for data loading
Example:
http://covid-19.demo.community.intersystems.com/dsw/index.html#/irisapp/Covid19/USA.dashboard

**Comment by Lena-Ev** [comment]
@evshvarov could you provide an example pls

**Comment by Lena-Ev** [comment]
https://covid-19.demo.community.intersystems.com/dsw/index.html#/USER/Covid19/USA.dashboard

**Comment by Lena-Ev** [comment]
https://dswmap.demo.community.intersystems.com/dsw/index.html#/USER/USA/USA%20Map%20Standard.dashboard

**Comment by gnibeda** [comment]
3.1.82
