### ISSUE TITLE
Can't share a widget

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#193]
[Here's](http://161.97.80.143:52777/dsw/index.html#/MAP/map/Map.dashboard) my dash.
I press `Share` on any widget, and get, for example, [this link](http://161.97.80.143:52777/dsw/index.html#/MAP/map/Map.dashboard?widget=2).
However it does not display anything.

**Comment by gnibeda** [comment]
fixed in 3.1.21
