### ISSUE TITLE
text misalignment in table

### ISSUE THREAD

**Issue by annietongisc** [intersystems-community/DeepSeeWeb#197]
Texts in table widget are randomly misaligned.
<img width="560" alt="Screen Shot 2021-08-17 at 12 04 35 PM" src="https://user-images.githubusercontent.com/61712169/129766520-ba9a7f65-91a3-4cde-bc09-32fd48e29d92.png">

**Comment by gnibeda** [comment]
@annietongisc, please provide link for docker image with reproducible bug

**Comment by Lena-Ev** [comment]
#264 duplicate
