### ISSUE TITLE
Pivot variable doesn't show in DeepSeeWeb dasboard

### ISSUE THREAD

**Issue by ukhinanna** [intersystems-community/DeepSeeWeb#200]
Pivot variable doesn't show in DeepSeeWeb dasboard.
However it works in DeepSee dasboard.

link: http://161.97.80.143:52777/dsw/index.html#/map/map/Map.dashboard

![photo_2021-08-19_17-49-18 (2)](https://user-images.githubusercontent.com/89201483/130090956-b147cd36-ff66-4e8b-aedd-b279473715b7.jpg)
![photo_2021-08-19_17-49-19](https://user-images.githubusercontent.com/89201483/130091002-48733231-fe97-44f8-8c21-feae279e4067.jpg)

**Comment by eduard93** [comment]
@gnibeda MDX for this dash contains pivot variable `selectedPeriod` (referenced as `$variable.selectedPeriod`):

```
{
	"MDX": "SELECT {%LABEL([crimeRegionD].[H1].[crimeGromadaL].CurrentMember.Properties(\"guid\"),\"COD_1\",\"\"),CROSSJOIN([Measures].[crimeTotal],{[PERIOD].[H1].[Period].&[$variable.selectedPeriod].LAG(1),[PERIOD].[H1].[Period].&[$variable.selectedPeriod]}),%LABEL(%CELL(-1,0) / %CELL(-2,0) - 1, \"PeriodToPeriod\", \"#%;\"),%LABEL(CROSSJOIN([Measures].[crimeTotal]/100,[PERIOD].[H1].[Period].&[$variable.selectedPeriod]),\"Pop\",\"#%;\")} ON 0,[crimeRegionD].[H1].[crimeRegionL].Members ON 1 FROM [CRIME]"
}
```

With `selectedPeriod` values being one of:
![image](https://user-images.githubusercontent.com/5127457/130785783-a8dfced3-8ee0-454d-afdc-b47f949e9d24.png)

So if the user chooses `липень 2021` (or it's a default one) we need to either send this MDX (replacing `$variable.selectedPeriod` with `105`) :

```json
{
	"MDX": "SELECT {%LABEL([crimeRegionD].[H1].[crimeGromadaL].CurrentMember.Properties(\"guid\"),\"COD_1\",\"\"),CROSSJOIN([Measures].[crimeTotal],{[PERIOD].[H1].[Period].&[105].LAG(1),[PERIOD].[H1].[Period].&[105]}),%LABEL(%CELL(-1,0) / %CELL(-2,0) - 1, \"PeriodToPeriod\", \"#%;\"),%LABEL(CROSSJOIN([Measures].[crimeTotal]/100,[PERIOD].[H1].[Period].&[105]),\"Pop\",\"#%;\")} ON 0,[crimeRegionD].[H1].[crimeRegionL].Members ON 1 FROM [CRIME]"
}
```

Or I can adjust mdx2json `POST /MDX` request to accept `VARIABLES` object which you need to supply:

```json
{
	"MDX": "WITH MEMBER $variable.selectedPeriod as 'value:105' SELECT {%LABEL([crimeRegionD].[H1].[crimeGromadaL].CurrentMember.Properties(\"guid\"),\"COD_1\",\"\"),CROSSJOIN([Measures].[crimeTotal],{[PERIOD].[H1].[Period].&[$variable.selectedPeriod].LAG(1),[PERIOD].[H1].[Period].&[$variable.selectedPeriod]}),%LABEL(%CELL(-1,0) / %CELL(-2,0) - 1, \"PeriodToPeriod\", \"#%;\"),%LABEL(CROSSJOIN([Measures].[crimeTotal]/100,[PERIOD].[H1].[Period].&[$variable.selectedPeriod]),\"Pop\",\"#%;\")} ON 0,[crimeRegionD].[H1].[crimeRegionL].Members ON 1 FROM [CRIME]",
    "VARIABLES": {
        "selectedPeriod": "105"
    }
}
```

What do you think?
