### ISSUE TITLE
Drilldown into row of pivot/barChart does not use sorting settings

### ISSUE THREAD

**Issue by ukhinanna** [intersystems-community/DeepSeeWeb#205]
link: http://161.97.80.143:52777/dsw/index.html#/map/map/Map.dashboard

Drilldown into row of pivot/barChart does not use sorting settings
However, drilldown sorting works in Analyzer and DeepSee dashboard
![photo_2021-08-19_17-49-20](https://user-images.githubusercontent.com/89201483/130092251-f4cb891e-613f-479a-beac-b99188ac3da5.jpg)

Full mdx:
SELECT [Measures].[Total] ON 0,ORDER([RegionD].[H1].[ RegionL].Members,Measures.[Total],BDESC) ON 1 FROM [FACTCUBE]

Drilldown mdx:
SELECT [Measures].[ Total] ON 0,ORDER([RegionD].[H1].[ RegionL].&[4].children,Measures.[Total],BDESC) ON 1 FROM [FACTCUBE] %FILTER [RegionD].[H1].[RegionL].&[4]

**Comment by evshvarov** [comment]
@Eduard, I think this could be a MDX2JSON issue

Чт, 19 авг. 2021 г. в 18:01, Ukhina Hanna ***@***.***>:

**Comment by eduard93** [comment]
@evshvarov, @agnybida DSW Drilldown loses `ORDER` function.

**Comment by gnibeda** [comment]
fixed in 3.1.23
