### ISSUE TITLE
Need option to devide region on rayons or gromadas when drilldown

### ISSUE THREAD

**Issue by ukhinanna** [intersystems-community/DeepSeeWeb#207]
link: http://161.97.80.143:52777/dsw/index.html#/map/map/Map.dashboard

We have hierarchical territory (region->rayon->gromada).
Need the functionality to draw whether rayon's borders or gromada's borders on the step of choosing the region.
For now we have the default functionality to draw only the rayon's borders when choosing the region.

Example of other map: 
https://regions.rnbo.gov.ua/report/info/atu

**Comment by Lena-Ev** [comment]
out of date
