### ISSUE TITLE
Add DRILLDOWN param in URL

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#208]
DSW supports FILTER url param for widgets.

Please add DRILLDOWN url param with the value being drilldown element

**Comment by eduard93** [comment]
DRILLDOWN:path1~path2

**Comment by gnibeda** [comment]
parameter "drilldown" (lower case), contains all drill paths separated by "~" character. parameter value should be escaped.

eg., for:
`drilldown=[crimeRegionD].[H1].[crimeRegionL].&[23]~[crimeRegionD].[H1].[crimeRayonL].&[56043]`
escaped version is to be:
`drilldown=%5BcrimeRegionD%5D.%5BH1%5D.%5BcrimeRegionL%5D.%26%5B23%5D~%5BcrimeRegionD%5D.%5BH1%5D.%5BcrimeRayonL%5D.%26%5B56043%5D`

**Comment by evshvarov** [comment]
You can omit [] for the sake of visibility.
MDX needs them only to deal with spaces

Чт, 2 сент. 2021 г. в 13:29, Anton Gnibeda ***@***.***>:

**Comment by gnibeda** [comment]
done in 3.1.24
