### ISSUE TITLE
Report DRILLDOWN/FILTER in url

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#209]
In embedded mode is it possible to report DRILLDOWN/FILTER values?

**Comment by eduard93** [comment]
Also please add CONTROL/VARIABLES reporting in URL.

**Comment by ssarkisy** [comment]
The idea is to have feedback from embedded widget to the parent application. One of the possibilities – change <iframe> ```src``` attribute to reflect the current widget state. It is possible by changing location.href of the widget app – it will be reflected in the ```src``` attribute of the <iframe>. 

Also, if there are any possibilities to communicate between the parent page and iframe'd widget – we can use them.

**Comment by gnibeda** [comment]
added in 3.1.24
