### ISSUE TITLE
Add DATASOURCE url param

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#210]
For at least datasource control add ability to pass it from URL

**Comment by eduard93** [comment]
DATASOURCE:value

**Comment by gnibeda** [comment]
parameter "datasource" (lower case). parameter value should be escaped.

eg., for:
`datasource=map/rayon_5weights.pivot`
escaped version is to be:
`datasource=map%2Frayon_5weights.pivot`

**Comment by gnibeda** [comment]
done in 3.1.24
