### ISSUE TITLE
Add NOHEADER param

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#211]
To show/hide header

![image](https://user-images.githubusercontent.com/5127457/131487453-9ab4a75b-4ead-402d-aa61-058eb75d23ff.png)

**Comment by eduard93** [comment]
Values 1/0

**Comment by eduard93** [comment]
Hide fullscreen button on embedded widgets

**Comment by gnibeda** [comment]
parameter "noheader" (lower case), eg.
"&noheader=1"

**Comment by gnibeda** [comment]
done in 3.1.24
