### ISSUE TITLE
Add VARIABLE param in URL

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#212]
To support pivot variables.

**Comment by eduard93** [comment]
VARIABLE - exists in DeepSee

**Comment by eduard93** [comment]
https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=D2IMP_ch_dashboards#D2IMP_dashboard_url_parameters

VARIABLE:variable_name.variable_value

**Comment by eduard93** [comment]
Pivot variable cannot contain spaces or punctuation

**Comment by eduard93** [comment]
VARIABLE:variable_name.variable_value~variable_name2.variable_value2

**Comment by gnibeda** [comment]
parameter "variables" (lower case). contains list of variables and values separated by "~" character. parameter value should be escaped.

eg.:
`&variables=selectedPeriod.105~testVariable.100`

**Comment by gnibeda** [comment]
done in 3.1.24
