### ISSUE TITLE
Map pop-up enhancements

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#213]
- [ ] Display pop up centered on a poligon, not in the upper left corner of a widget
- [ ] Remove pop up if the user presses `Back` button

Example: http://161.97.80.143:52777/dsw/index.html#/map/map/Map.dashboard

**Comment by eduard93** [comment]
![image](https://user-images.githubusercontent.com/5127457/131547377-5db01d7c-659d-4f8e-89c6-c39959e7c6e0.png)

**Comment by eduard93** [comment]
Use `popupProperty`

![image](https://user-images.githubusercontent.com/5127457/131819200-a6968e1a-b777-4218-930c-c6ebb8d23396.png)

**Comment by gnibeda** [comment]
done in 3.1.24
