### ISSUE TITLE
Can't share some widgets

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#214]
Can share: http://161.97.80.143:52777/dsw/index.html#/MAP/map/Map.dashboard?widget=2

Can't share (does not load): http://161.97.80.143:52777/dsw/index.html#/MAP/map/Map.dashboard?widget=1

No idea why.

**Comment by eduard93** [comment]
Actually can't share any widget besides the second one (map)

**Comment by gnibeda** [comment]
done in 3.1.24
