### ISSUE TITLE
Termlist using as control doesn`t show in DSW Dashboard

### ISSUE THREAD

**Issue by ukhinanna** [intersystems-community/DeepSeeWeb#215]
link: http://161.97.80.143:52777/dsw/index.html#/map/map/Map.dashboard

This contol works correctly when it locates on widget.
Still control doesn`t show when it locates on DSW dashboard. However, it show on DS dashboard

**Comment by gnibeda** [comment]
As discussed with @eduard93, we don't need it currently.
Do you still need this feature?

**Comment by OlgaBorokhova** [comment]
We don't need it currently but itseem to be good  for DSW in general.

**Comment by Lena-Ev** [comment]
We will reopen when get another request
