### ISSUE TITLE
Show "displayName" of cube level when drill down the map

### ISSUE THREAD

**Issue by OlgaBorokhova** [intersystems-community/DeepSeeWeb#216]
Now "name" of cube level display when drill down - [crimeRayonL]
link http://161.97.80.143:52777/dsw/index.html#/map/map/Map.dashboard

![new1](https://user-images.githubusercontent.com/89194394/131980909-6c870307-4321-4d1c-a5cb-1babd2b3550b.PNG)

![new2](https://user-images.githubusercontent.com/89194394/131980698-72585485-bfe2-40a7-8afc-c0546c7493c1.PNG)

**Comment by eduard93** [comment]
If it's not possible maybe hide it altogether (all hide everything but the last level for which displayname is known)?

**Comment by OlgaBorokhova** [comment]
Don't need it now (problem was solved via UI) but it will be good for DSW in general.
