### ISSUE TITLE
Add `tooltipProperty` dataProperty

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#220]
To display value on hover

**Comment by evshvarov** [comment]
Already exits: TooltipValue field?

Вт, 7 сент. 2021 г. в 11:01, Eduard ***@***.***>:

**Comment by eduard93** [comment]
@evshvarov how can I set properties on widgets and not dataProperties?

**Comment by evshvarov** [comment]
This is not a “map” case, right?
It’s just not clear according to the description.


Вт, 7 сент. 2021 г. в 16:30, Eduard ***@***.***>:

**Comment by eduard93** [comment]
We need it for a map.

**Comment by gnibeda** [comment]
added in 3.1.27
`TooltipValue` is default name of column that used for tooltips, but with `tooltipProperty` you can define any field to use as tooltip.
