### ISSUE TITLE
Support horizontal controls on dashboards

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems-community/DeepSeeWeb#223]
It looks like DeepSeeWeb doesn't currently support displaying controls in a horizontal layout. The "horizontalControls" widget gets rendered with a vertical layout, and so does the "Filters" box that is created when controls have location dashboard. 
It would be nice to support this to allow e.g. a horizontal row of filters displayed on the top of a dashboard.

**Comment by Lena-Ev** [comment]
@evshvarov could you please make an example for that

**Comment by evshvarov** [comment]
I did!
[Here it is.](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Bug/Support%20Horisontal%20panel.dashboard)
But turned out @gnibeda already implemented it.
@isc-pbarton , could you please check?

**Comment by Lena-Ev** [comment]
Now you can set up horizontak view of the filter  in 1,2 and 3 columns
use the icons in the upper right corner of the widget 


![Image](https://user-images.githubusercontent.com/77621970/226128763-4b85216c-efa1-48fd-89b1-57d53a7982ce.png)
