### ISSUE TITLE
Hide context menu on the map widget

### ISSUE THREAD

**Issue by OlgaBorokhova** [intersystems-community/DeepSeeWeb#225]
Add the ability to hide context menu on the map widget
![context menu](https://user-images.githubusercontent.com/89194394/138702992-479f249e-f16c-41c4-a1d9-f43c6532479e.PNG)

**Comment by gnibeda** [comment]
implemented in 3.1.33
* added url parameter for shared widgets `disableContextMenu`, when set to "1" disables context menu on shared widget
* added data property `disableContextMenu`, when set to "1" disables context menu on widget
