### ISSUE TITLE
Pie chart - percentage precision

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#229]
Is it possible to set precision on pie charts percentages?

![image](https://user-images.githubusercontent.com/5127457/142607453-6cc6e853-7630-422c-8fd1-2593725008de.png)

We need it rounded to one fractional digit.

**Comment by eduard93** [comment]
Are we using `GET /Format`. Maybe something there? 
Or in namespace settings?

**Comment by gnibeda** [comment]
Can you extend the `Info`  part of the response, that contains decimal separators, etc.?

**Comment by gnibeda** [comment]
implemented in 3.1.35
* added `percentageFormat` data property, to set format of percents for widgets that show percentage values, e.g. `#.##`
