### ISSUE TITLE
Implement embedding widgets by unique Id or name

### ISSUE THREAD

**Issue by ssarkisy** [intersystems-community/DeepSeeWeb#230]
Now widgets are embedded by refercing to them by order number, e.g. ?widget=0 or ?widget=2.
It's dangerous because changes in dashbord could lead to unexpected changes in embedded widgets.
It would be better to reference to widgets by name or unique id.

**Comment by gnibeda** [comment]
implemented in 3.1.35
* now shared widgets use name instead of index, e.g. `http://test.com/#/MAP/map/Map.dashboard?widget=UAMap.geojson`

**Comment by Lena-Ev** [comment]
@ssarkisy reopen if you have any questions
