### ISSUE TITLE
Map. Display the values on the polygons

### ISSUE THREAD

**Issue by ukhinanna** [intersystems-community/DeepSeeWeb#231]
Display the values on the polygons, for example
![picture_criminal-ukraine_3046_p0](https://user-images.githubusercontent.com/89201483/143058995-0b555ee9-0685-4965-b911-4e53e8000514.png)
Be able to control the font size and format.

link http://161.97.80.143:52777/dsw/index.html#/map/map/Map.dashboard

**Comment by gnibeda** [comment]
implemented in 3.1.35
* added `dataLabels` data property for map widget.
 now values can be displayed directly on map.
set `dataLabels=1` to show values. `dataLabels` can be set to JSON with options to customize labels,
default values is:
 ```{ "size": 12, "font": "Calibri,Arial,sans-serif", "color": "#000", "stroke": "#FFF", "strokeWidth": 2 }```.
options can be defined in any combinations, e.g. `{ "color": "#F00", "size": 18 }`

**Comment by Lena-Ev** [comment]
@ukhinanna reopen if you have any questions
