### ISSUE TITLE
Different barChart view of 0

### ISSUE THREAD

**Issue by OlgaBorokhova** [intersystems-community/DeepSeeWeb#233]
Pivot (barChart based on) in Analyzer show 0 in each cel
![image_2021_11_29T09_28_13_857Z](https://user-images.githubusercontent.com/89194394/143847958-d1a61424-7b6b-4c44-a0d7-f759ad14e287.png)

barChart 1st PC
![бахчисарайский](https://user-images.githubusercontent.com/89194394/143848072-3cd2b259-8726-4297-b139-01ea42ede0ef.PNG)

barChart 2nd PC
![image_2021_11_29T09_28_52_561Z](https://user-images.githubusercontent.com/89194394/143848212-dfb197d9-fd28-4c40-987a-a54517718d08.png)

It needs the same view for all PC, users, browsers, etc.

**Comment by Lena-Ev** [comment]
@gnibeda update highchart version and we will see if that will help.

**Comment by gnibeda** [comment]
Highcharts updated in 3.1.47
