### ISSUE TITLE
Demo/EmbedOnly mode

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/DeepSeeWeb#234]
Is there a way to build DSW (or configure on the server side via additional file for example) so it would work:
1. Only showing embedded widgets.
2. Not allowing user to change anything locally (no menu to  change colors etc).

**Comment by eduard93** [comment]
MDX2JSON now returns `Embed` property in `GET /MDX2JSON/Test`.

It if's empty (or missing) DSW works as is. 
If it's set it must be set to dashboard name. In that case DSW works only for this dash and only in embed mode. 
To set Embed property set the global `^MDX2JSON.Embed` or `^%MDX2JSON.Embed`.

**Comment by gnibeda** [comment]
implemented in 3.1.39
