### ISSUE TITLE
Enhancements for the Map Addon

### ISSUE THREAD

**Issue by tnitzsch** [intersystems-community/DeepSeeWeb#24]
Currently, there is a working sample addon available for maps that shows highlighted countries based on a metric. Please support the following cases: 
1 world map drill down from world to state
2 world map drill down with additional information (PINs within State)
3 world map drill down with additional information (bubbles within State)
4 Additional information based on another metric (on a click within the map show rich information in a second widget)

Thank you!

**Comment by eduard93** [comment]
[Here are more detailed maps](https://github.com/intersystems-ru/dsw-map)

**Comment by evshvarov** [comment]
This is about world map addon, which is a separate thing.
