### ISSUE TITLE
Scorecards don't display properly with DeepSeeWeb

### ISSUE THREAD

**Issue by wolfman0719** [intersystems-community/DeepSeeWeb#247]
Scorecards created in User Portal  do not display properly with DeepSeeWeb.
Only the frame of the scorecard is displayed, but the content is not displayed at all.
The scorecards are displayed correctly in the User Portal of the Management Portal.
Attached is a very simple scorecard definition that reproduces the problem.
The data source is a KPI included in samples-bi.
[test-dashboard.zip](https://github.com/intersystems-community/DeepSeeWeb/files/8489434/test-dashboard.zip)

**Comment by evshvarov** [comment]
Hi @wolfman0719 !
Is this what is expected to see?
<img width="472" alt="Screenshot 2022-10-22 at 11 19 08" src="https://user-images.githubusercontent.com/2781759/197356691-a3139882-0f7d-46a1-8e67-d1f4873e9759.png">

Some scorecards work in DSW, check [this one](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/Sales%20Against%20Targets.dashboard).

**Comment by wolfman0719** [comment]
Yes
I seems that old scorecards that were built on Cache work fine.
I haven't had an expected result with a scorecard defined on IRIS when it comes to showing with DeepSeeWeb

**Comment by Lena-Ev** [comment]
@jakcpto could you please reproduce xml and create an example for Anton?

**Comment by jakcpto** [comment]
Sent pull request for demo reproduction https://github.com/evshvarov/Samples-BI/pull/1

**Comment by jakcpto** [comment]
@gnibeda look at https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/test.dashboard

**Comment by Lena-Ev** [comment]
to rewrite the widget with new example

**Comment by Lena-Ev** [comment]
is that KPI issue duplicate?

**Comment by evshvarov** [comment]
The were some fixes in KPI support. Can you test with the latest version?

**Comment by Lena-Ev** [comment]
Does it look good??


![Image](https://user-images.githubusercontent.com/77621970/211799689-1aa4b6f3-a042-4588-8ce5-03bfc74d88c7.png)

**Comment by gnibeda** [comment]
This is how it looks in Iris BI:
![image](https://user-images.githubusercontent.com/9804674/212188106-a7fa2242-fdc2-4ec7-8c38-2a680af6c82c.png)

**Comment by gnibeda** [comment]
"Plot Box" should be supported, "Arrow" - no. Can you provide an example, we will implement it asap

**Comment by wolfman0719** [comment]
[KPIs_&_Plugins-Sales_Against_Target_2-dashboard.zip](https://github.com/intersystems-community/DeepSeeWeb/files/10416365/KPIs_._Plugins-Sales_Against_Target_2-dashboard.zip)
I create an sample similar to the Sales_Against_Target in the BI Samples.
I added 2 scorecards column, a plot box and a  % Value
The % Value is not displayed as I expect as well.

**Comment by evshvarov** [comment]
@wolfman0719  @gnibeda - here is the reproduced example: https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/Sales%20Against%20Target%202.dashboard

**Comment by Lena-Ev** [comment]
The data should be presented in an empty column here:


![Image](https://user-images.githubusercontent.com/77621970/213160121-ad1bfe25-5d66-4407-85dc-a030787c65fc.png)

**Comment by evshvarov** [comment]
@wolfman0719 this is solved in 3.1.60 - please check?

**Comment by Lena-Ev** [comment]
This is how it works on example 
<img width="986" alt="image" src="https://user-images.githubusercontent.com/77621970/214553272-7cad80e3-c570-406b-a12d-19a4eda358c5.png">
