### ISSUE TITLE
Stacked Bar Chart doesn't display properly in DeepSeeWeb

### ISSUE THREAD

**Issue by Yooshkimchi** [intersystems-community/DeepSeeWeb#252]
The stacked bar chart will display as intended in the management portal, but in DeepSee, the bar will be one solid color. 
The data also appears completely different in DeepSee.

Management Portal:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/49344292/183993733-18bc8533-ac71-4a66-b157-4d09bf8d754f.png)

DeepSee:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/49344292/183993783-31910d55-7c4c-4985-a1dd-fae0b97ee207.png)

**Comment by evshvarov** [comment]
Could you please share the sample data-cube-pivot-dashboard?
What is the dsw version?

**Comment by Yooshkimchi** [comment]
This is the link to the dashboard in BASE: https://base.appsight.iscinternal.com/dsw/index.html#/APPSIGHT/SSO/SSOUsage.dashboard

The stacked bar graph should be the 3rd graph

**Comment by evshvarov** [comment]
Please, ping me in teams, Evgeny Shvarov

**Comment by evshvarov** [comment]
DSW doesn't support column headers that contain only numbers in their names
