### ISSUE TITLE
Request for Fixes

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#254]
- [ ] DSW is not able to display all possible DeepSee widget configurations. - need specification
- [ ] Some DeepSee widget features are not supported, so DSW can’t display complex widgets.  -  need specification
- [x] Secondary axes on graph charts;
- [ ] #279
- [x] Chart titles are not supported;
- [ ] #281
- [x] OnClick filters on charts work only with drilling down;
- [x] Meter widgets are not supported;
- [x] Scorecard widgets are not supported;
- [x] Crossjoins on charts are not properly displayed
- [ ] #282

**Comment by evshvarov** [comment]
[Scorecards](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/Sales%20Against%20Targets.dashboard)

**Comment by Lena-Ev** [comment]
Not finished tasks are transformed into other issues
