### ISSUE TITLE
Control for filter only works for one widget

### ISSUE THREAD

**Issue by annietongisc** [intersystems-community/DeepSeeWeb#260]
I'm trying to add a control to a pie chart where if I click on a slice, it adds filters to two different stacked bar chart. This works OK in embedded BI dashboard but in DSW only one bar chart is changing based on the filter.

**Comment by evshvarov** [comment]
Made a [demo](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Bug/ClickFilter.dashboard) for the bug
@gnibeda , could you please solve ASAP?

**Comment by gnibeda** [comment]
fixed in 3.1.42
