### ISSUE TITLE
Listing pivot table mismatch

### ISSUE THREAD

**Issue by annietongisc** [intersystems-community/DeepSeeWeb#262]
I tried to save a listing that's a custom SQL query as a pivot table (there are other listings in the cube and this is not the default listing). The pivot table works fine in embedded BI dashboard but DSW is showing the default listing instead.

**Comment by evshvarov** [comment]
I made a [demo](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Bug/NonDefault%20Listing.dashboard) for this. @gnibeda , please take a look?

**Comment by MakarovS96** [comment]
Hi @gnibeda! You can modify MDXDrillthrough query using %LISTING [ListingName]    
e.g. "DRILLTHROUGH SELECT FROM [HOLEFOODS] %FILTER [DateOfSale].[Actual].[YearSold].&[2021] %LISTING [ListingX]"
In this case, you can get the name of the listing from the Dashboard query, from the widget controls _(Dashboard  widgets.[x].controls.[y].{action:"showListing", targetProperty:"ListingX"})_, if the listing was set in the control.     
Or you can find the listing in the DataSource query _(field "listing")_ response if listing was set in the pivot

**Comment by gnibeda** [comment]
Done in 3.1.47
