### ISSUE TITLE
"no data to display" when select a filter value that's not the default value in a widget

### ISSUE THREAD

**Issue by annietongisc** [intersystems-community/DeepSeeWeb#263]
This is working fine in embedded BI. This is not working for the individual widgets on DSW, as well as the entire dashboard (if I set the control to be the entire dashboard)

**Comment by evshvarov** [comment]
You need to be out of ISC VPN

**Comment by MakarovS96** [comment]
@adaptun Could you please explain if this is a bug or a feature?)

We found bug in DeepSee. %OR doesn't work for calculated dimensions.

Example request:
SELECT NON EMPTY [Measures].[Amount Sold] ON 0,NON EMPTY [DateOfSale].[Actual].[YearSold].Members ON 1 FROM [HOLEFOODS] %FILTER %OR({[MyRegion].&[North] })

Server with example:
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Bug/Default%20Filter%20Issue.dashboard

![image](https://user-images.githubusercontent.com/19629483/196703488-0f7b0c67-850f-42ff-bacd-db748cd2c990.png)

**Comment by adaptun** [comment]
@MakarovS96 this does not work in 2022.1, but fixed in the 2022.2 (Build 356U)
