### ISSUE TITLE
Support Navigate button

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#271]
There is Navigate button that helps to open another dashboard

**Comment by evshvarov** [comment]
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Basic%20Dashboard%20Demo.dashboard)

**Comment by gnibeda** [comment]
done in 3.1.46

**Comment by evshvarov** [comment]
Works
