### ISSUE TITLE
Introduce support for Radio button option for the filters

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#274]
as alternative to dropdowns

**Comment by evshvarov** [comment]
Reproduced [here](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Basic%20Dashboard%20Demo.dashboard)

**Comment by gnibeda** [comment]
done in 3.1.46

**Comment by evshvarov** [comment]
This approach needs an extra-click for the user - to click on the filter first, and then choose the radio.
Is it possible to show radio buttons instead?
But please, take a moment we'll check with users if they like the current implementation

**Comment by evshvarov** [comment]
It’s OK
