### ISSUE TITLE
Support pivot-view mode setting for Graph widgets

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#275]
Now all graph widgets are shown as graph, even in table mode.
Here is the [reproduced example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Basic%20Dashboard%20Demo.dashboard).
DSZ:
<img width="990" alt="Screenshot 2022-10-28 at 11 06 28" src="https://user-images.githubusercontent.com/2781759/198668342-44e83ad9-b4ed-4880-b665-459a9a112274.png">

DSW:
<img width="1209" alt="Screenshot 2022-10-28 at 11 06 02" src="https://user-images.githubusercontent.com/2781759/198668083-c88e4086-a198-4564-9feb-bfe9a772ce7a.png">

**Comment by gnibeda** [comment]
done in 3.1.46

**Comment by evshvarov** [comment]
Works
