### ISSUE TITLE
ComboChart doesn't follow chart types: shows line instead of colchart

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#276]
[Reproduced example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Widget%20Examples/Linked%20Widgets.dashboard)

**Comment by evshvarov** [comment]
<img width="818" alt="Screenshot 2022-10-27 at 16 21 48" src="https://user-images.githubusercontent.com/2781759/198672485-c77577bb-82eb-4885-8390-2b7d88d07d00.png">
This is in DSZ

**Comment by evshvarov** [comment]
<img width="814" alt="Screenshot 2022-10-28 at 11 14 48" src="https://user-images.githubusercontent.com/2781759/198672580-ec10815a-696f-4bf8-b0cd-44ef61627e8d.png">

**Comment by gnibeda** [comment]
dome in 3.1.46

**Comment by evshvarov** [comment]
works
