### ISSUE TITLE
Support Color Formatting for Text Meters

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#277]
Lower and upper thresholds are set, if the number is smaller than the lower threshold then “low style” (red) is applied. If higher than higher threshold, then “high style” (green) is applied. If neither, meaning the value is between thresholds then “style” is applied and it’s set to yellow:
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Widget%20Examples/Meters%20A.dashboard)
This is how it looks in DSZ:
![image](https://user-images.githubusercontent.com/2781759/200033335-7b03d4aa-b212-4841-bc66-089d9aaae1ee.png)
THis is DSW:
<img width="949" alt="Screenshot 2022-11-04 at 13 05 53" src="https://user-images.githubusercontent.com/2781759/200033407-1d205f32-6885-459d-be0a-8ff0df1a5562.png">

**Comment by gnibeda** [comment]
Done in 3.1.47
