### ISSUE TITLE
Error when trying to install DSW

### ISSUE THREAD

**Issue by MIXMARLEON** [intersystems-community/DeepSeeWeb#280]
I tried to install DSW using Node.js v18.12.0
```
npm i
npm run start
```

including clearing cache and reinstalling packages.

```
npm install --global npm@6
npm install -g npm@7.22.0
npm install --global npm
npm cache clean --force
npm cache verify
npm install --force
```

Removed _package-lock.json_, _node_modules_ in project,
_C: \Users\[user]\AppData\Roaming\npm
C:\Users\[user]\AppData\Roaming\npm-cache_

In all cases, the following error occurs when executing npm run start.
![Code_3wT8kTNsPX](https://user-images.githubusercontent.com/45977278/200807247-35075989-cbd5-4368-b820-d5b427c90308.png)

**Comment by Lena-Ev** [comment]
Text directly to Anton

**Comment by Lena-Ev** [comment]
try to use Node 16.3.0

**Comment by jakcpto** [comment]
@Lena-Ev I think someone should to add a notion in README about the number of suitable Node.js version.
After that newbies like us can run DSW without asking for help.

**Comment by jakcpto** [comment]
Lets reopen this just not to forget.

**Comment by evshvarov** [comment]
That’s why i was talking about contribution.md.
Btw, is it possible to upgrade to the latest version of node?

**Comment by Lena-Ev** [comment]
@gnibeda could you please add notion to READ ME as Eugeny asks?
