### ISSUE TITLE
Widget controls different from basic «applyFilter» are not supported (e.g.: «setPivotVariable», «setRowSpec»);

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#281]
need example

**Comment by evshvarov** [comment]
added an example for [SetFilter](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Bug/SetFilter.dashboard). Region is a SetFilter.
The idea is that SetFilter changes the filter but doesn't execute. It is being executed with any other filter or refresh button.
