### ISSUE TITLE
update README about the number of suitable Node.js version.

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#284]
@Lena-Ev I think someone should to add a notion in README about the number of suitable Node.js version.
After that newbies like us can run DSW without asking for help.

_Originally posted by @jakcpto in https://github.com/intersystems-community/DeepSeeWeb/issues/280#issuecomment-1309874332_

**Comment by evshvarov** [comment]
It is better introduce into contribution.md

**Comment by gnibeda** [comment]
Done in 3.1.55
