### ISSUE TITLE
KPI for MDX doesn't work

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#290]
Changing the filter causes problem:
<img width="963" alt="Screenshot 2022-11-16 at 5 12 10 PM" src="https://user-images.githubusercontent.com/2781759/202233623-1d2825d7-c5c2-4187-a469-342296e61838.png">

Reproduced [here](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/Demo%20Filter%20Interoperability.dashboard):

**Comment by Lena-Ev** [comment]
@jakcpto посмотри пожалуйста, что тут не так с МДХ, пока Антону не понятно, какой он должен быть

**Comment by jakcpto** [comment]
Bottom widget has no MDX at all.
I think this is a bug and the reason of error message.
![image](https://user-images.githubusercontent.com/41373877/206484216-5330530f-00f3-4ae4-82eb-118d459f1503.png)

Top widget have this MDX
![image](https://user-images.githubusercontent.com/41373877/206484602-f97331ea-ac2d-4c39-accc-69369772bd90.png)

And when I'm choosing a filter in the top widget, filter applies to both widgets.
And in that case top widget have correct MDX (with filter added), but bottom has corrupted MDX (only filter without SELECT).

**Comment by gnibeda** [comment]
There is no MDX, because the bottom widget has KPI, and executes request `/MDX2JSON/KPI?Namespace=irisapp` with payload `{"KPI":"DemoInteroperability.kpi"}`. Filters for KPI is not implemented in DSW,
I need a way to apply filters to KPI requests. Can you explain how it can be done in mdx2json?

**Comment by jakcpto** [comment]
@gnibeda now we have formed /KPI endpoint so DSW can send FILTERS in payload and the results will be filtered.

Example:
{   "KPI":"DemoInteroperability.kpi",
    "FILTERS":[
        {"name":"[ColorD].[H1].[Favorite Color]", "value":"Green"},
        {"name":"[DocD].[H1].[Doctor Group]", "value":"I"}
    ]
}

There is array of objects.
It can be array of only one object.
"name" and "value" are keys.
Name refers to a "path" parameter from filters response.

For multiple selection of one filter, add another object in array:

{   "KPI":"DemoInteroperability.kpi",
    "FILTERS":[
        {"name":"[ColorD].[H1].[Favorite Color]", "value":"Green"},
        {"name":"[ColorD].[H1].[Favorite Color]", "value":"Yellow"},
        {"name":"[DocD].[H1].[Doctor Group]", "value":"I"}
    ]
}

**Comment by jakcpto** [comment]
@Lena-Ev FYI.
This is important issue, can solve critical project task.

**Comment by gnibeda** [comment]
Done in 3.1.63

**Comment by Lena-Ev** [comment]
@evshvarov check pleaase
