### ISSUE TITLE
Listing doesn't work for KPIs

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#291]
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/KPI%20with%20Listing.dashboard)

**Comment by Lena-Ev** [comment]
@jakcpto 
the same question here - whats wrong with MDX, seems like the problem goes from back.
How should it work correctly?
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/77621970/206434435-4ff66d24-ec0f-408d-b00d-a488b3e61c8a.png">

**Comment by Lena-Ev** [comment]
Request needed which will allow to make request for KPI drillthrough

**Comment by Lena-Ev** [comment]
MDX based KPI - mdx drill through
SQL based KPI - new approach? **end point for KPI-drill through**
KPI - type from MDX2JSON
new MDX2KSON method

**Comment by Lena-Ev** [comment]
re-work to keep secure

**Comment by Frisle** [comment]
@evshvarov take a look on this code. Eduard says that we have to take sql directly from kpi. What if we try this?
![Screenshot 2023-02-24 135314](https://user-images.githubusercontent.com/47441164/221122898-f95d77bd-dffd-472b-a9a8-6446fa2ddf82.png)

TestSQL gets the kpi name, fetches the sql, checks the sql query if everything is ok and returns it for further execution

**Comment by evshvarov** [comment]
@eduard93 means that end-point shouldn't expect SQL. 
Could the end-point expect kpiname and necessaary params and then SQL will be formed from KPI callback on the server side?

**Comment by Frisle** [comment]
@evshvarov yes it can. Work still in progress but here the preliminary result
![Screenshot 2023-02-24 165132](https://user-images.githubusercontent.com/47441164/221161406-4897a912-16a9-4167-bc3e-040475b4b241.png)

**Comment by Lena-Ev** [comment]
format - drill through
Parameter Drillthrough:1 ...

**Comment by Frisle** [comment]
Made quick changes to REST. KPI endpoint changed as requested
https://github.com/intersystems-ru/Cache-MDX2JSON/pull/98/files#:~:text=%7D-,ClassMethod%20KPIExecute()%20As%20%25Status,%7D,-///%20Wrapper%20for%20%23%23class

**Comment by Lena-Ev** [comment]
to check

**Comment by Lena-Ev** [comment]
@evshvarov checj after release

**Comment by Lena-Ev** [comment]
@eduard93 could you please merge this update

**Comment by evshvarov** [comment]
where we are here?

**Comment by Frisle** [comment]
@evshvarov the new method gets values from KPIs, but tables are not displayed due to missing properties. At the moment, the method has returned what the KPI contains. Are these KPI issues or do we need to work on this further to get properties?
![Screenshot 2023-04-06 161512](https://user-images.githubusercontent.com/47441164/230348823-09d2ab82-d445-42ca-b1ad-fbe9ab4faae5.png)

**Comment by Lena-Ev** [comment]
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/KPIs%20&%20Plugins/KPI%20with%20Listing.dashboard)

**Comment by Lena-Ev** [comment]
find parser - columns sql

**Comment by Frisle** [comment]
![Screenshot 2023-04-14 213148](https://user-images.githubusercontent.com/47441164/232748021-c8d59a54-559a-4ef4-89ea-de8164d372b9.png)

**Comment by Frisle** [comment]
Here is the final result
![chrome_j5j2YdyF1j](https://user-images.githubusercontent.com/47441164/234234002-55aa58ca-0a4f-4787-af7d-25581e7c06eb.gif)

**Comment by evshvarov** [comment]
Super!

**Comment by Frisle** [comment]
The new method is on pie-chart already

https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/KPIs%20&%20Plugins/KPI%20with%20Listing.dashboard

The reason that only one column is shown is because the data properties only match on the product column, and the other three are not provided by the data source, which is a KPI

**Comment by Lena-Ev** [comment]
- [ ] Ignore data property while drill through for KPI

- [ ] back button

**Comment by gnibeda** [comment]
Done in 3.1.88

**Comment by evshvarov** [comment]
works!
