### ISSUE TITLE
KPI: some filters do not show the values

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#294]
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/SQL%20Based%20KPI.dashboard) - here Zip Code filter doesn't show its members

**Comment by evshvarov** [comment]
[Second example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/KPI%20with%20Switchable%20Rows.dashboard)

**Comment by gnibeda** [comment]
Mdx2json returns an invalid result for the filter requests.
Request: `/MDX2JSON/Filters?Namespace=IRISAPP`
Payload: 
```json
{"DataSource":"Holefoods/SalesAgainstTargets.kpi","Values":1,"Search":"","RequestedFilters":["ShowBy"]}
```
Invalid JSON result: 
```
{
"children":[
	{null
```

**Comment by evshvarov** [comment]
@eduard93, just in case you have time, can you please have a look?

**Comment by evshvarov** [comment]
Here is the class that is responsible for the KPI where filters don't work: https://github.com/evshvarov/Samples-BI/blob/master/src/BI/Model/KPIs/DemoInteroperability.cls#L0-L1

**Comment by Lena-Ev** [comment]
More info about KPI needed:
1 - Are there any standards to write KPI code?
2 - When users need to use KPI instead of pivot? Are there filters needed in the KPI data at all? 
3 - What are the real scenarios to use KPI? To make workaround to add filters to this data

@evshvarov Could you help please or connect to the users who use KPI and face with filtering problem right now

**Comment by Lena-Ev** [comment]
check call back from the case abovw with evgeny

**Comment by jakcpto** [comment]
We need to make a custom solution to workaround response from https://github.com/evshvarov/Samples-BI/blob/a66a939af79f287aa0f7fc68fedb092651e90a80/src/BI/Model/KPIs/DemoInteroperability.cls#L48

**Comment by Frisle** [comment]
My recent hack fixed the appearance of filters. Filled in json in Holefoods/SalesAgainstTargets.kpi and drop down menu in DemoInteroperability.kpi

![Postman_NpZUTwgn05](https://user-images.githubusercontent.com/47441164/215005569-5c08e478-b545-4efe-865a-a3a2be8c967b.gif)

The hack https://github.com/teccod/MDX2JSON/pull/5

**Comment by jakcpto** [comment]
@gnibeda take a look why filters don't send requests for filter members?
For example https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/MDX%20Based%20KPI.dashboard and https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/SQL%20Based%20KPI.dashboard

(MDX Based KPI and SQL Based KPI)

They are only loading icons while opening filter popup, nothing else.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/41373877/216101899-d0983295-cedf-4c77-b360-a58feb0db557.png">

**Comment by gnibeda** [comment]
Done in 3.1.63

**Comment by evshvarov** [comment]
fixed!
