### ISSUE TITLE
Filters do not work!! Urgent!

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#295]
Exclusive filter with one element is being selected if you choose the title and not checkbox. it cancels previous filter set and sets the new element. This is still working. But filters chose by checkbox are broken and not working.

**Comment by evshvarov** [comment]
done

**Comment by evshvarov** [comment]
It looks like it doesn't work in some cases.
Here is the screen recording video
https://www.loom.com/share/96437ca039774e50a4bffa2fa24468bc

**Comment by jakcpto** [comment]
Look at http://public-analytics.community.intersystems.com/dsw/index.html#/DCANALYTICS/BasicDashboards/Posts.dashboard

**Comment by gnibeda** [comment]
It works on a provided example. 
Please check, can we somehow limit requests for filter values so only the first N records are returned?
Seems that issue can occur in this case.

**Comment by jakcpto** [comment]
@evshvarov are you talking about [example](http://public-analytics.community.intersystems.com/dsw/index.html#/DCANALYTICS/BasicDashboards/Posts.dashboard) below?

I believe there are all the authors having posts published.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/41373877/207380660-d40ed3c0-3229-4083-93ed-9643d07de920.png">

**Comment by jakcpto** [comment]
All values load but not all displayed.

While opening last item is Ruth Freeman
![Image](https://user-images.githubusercontent.com/41373877/208834933-686b446c-1294-48a1-998e-ef2157c1c17a.png)

But in Filter I can choose someone with "Y" at the beginning


![Image](https://user-images.githubusercontent.com/41373877/208835157-a51e01af-67da-4178-ac92-58625a9733e6.png)

@gnibeda can you take a look on this?

**Comment by jakcpto** [comment]
UPD: Seems that Backend limiting output size.
Direct queries to MDX2JSON returns the same that we can see in DSW filters population.

Now we are looking how to increase this limit.

**Comment by jakcpto** [comment]
Strange thing found in %DeepSee/Dashboard/Utils.cls/%GetMembersForFilter
There is upper limit on the members amount equal to 2500.

![Image](https://user-images.githubusercontent.com/41373877/212254498-f055a92b-f546-4d2d-a1c9-38c1a9c1a2c4.jpg)

So currently Ron Mitchell has ordinal number about 2500 in the list of the Filter.

![Image](https://user-images.githubusercontent.com/41373877/212255141-436c0b38-1bf4-42c9-afb7-d84cb5c263ea.jpg)

@evshvarov I think we cannot change the constant in %DeepSee/Dashboard/Utils.cls/%GetMembersForFilter?

**Comment by evshvarov** [comment]
why public analytics don't show all the members? there are more than 2,500

**Comment by jakcpto** [comment]
> why public analytics don't show all the members? there are more than 2,500

Because of default filters about Time Measures in Public DC Analytics there are less members available to select.

**Comment by jakcpto** [comment]
Waiting for https://github.com/intersystems-community/dc-analytics/pull/47 to be merged.

**Comment by jakcpto** [comment]
@gnibeda take a look at http://public-analytics.community.intersystems.com/dsw/index.html#/DCANALYTICS/Total%20member.dashboard

Now you can have development on this demo stage.



![Image](https://user-images.githubusercontent.com/41373877/213156043-9bfcfa7a-9a4c-426c-9eb5-05d5ed083feb.png)

**Comment by Lena-Ev** [comment]
@jakcpto Could you update to the latest DSW version?

**Comment by Lena-Ev** [comment]
@jakcpto could you please leave a comment what doesn't work from Anton;s side Do we need fixes on front end side?

**Comment by jakcpto** [comment]
@evshvarov the portal updated to the latest DSW.

@Lena-Ev I think we can close this issue, because behavior of filters is normal now. And the 2500 limit is a platform limit we cannot move and it is not necessary.

**Comment by evshvarov** [comment]
the problem is in DSW.
when the filter is limited it is not possible to select several elements.
anton asked to reproduce the case with filter elements on limit.
you did.
now let’s fix the issue?)

**Comment by gnibeda** [comment]
@evshvarov, despite the fact that it is still not working. 
> ![Image](https://user-images.githubusercontent.com/77621970/215732585-0f9aa4f7-20a8-4f31-906c-d8f9ff2173d6.png)

multiple filters work fine in this example. what is your case?

**Comment by evshvarov** [comment]
Guys, please help me.
I found an issue.
I suggested how to reproduce the problem.
Anton, Evgeny, please help?
Problem exists now on the community analytics (not public) - solve it
without me please?

**Comment by gnibeda** [comment]
@jakcpto, please update DSW to the last version 3.1.62

**Comment by gnibeda** [comment]
DSW updated to 3.1.62. Please chek filters
![filters](https://user-images.githubusercontent.com/9804674/215858268-0ae6a161-38d4-4c43-8226-6ffc5d337d6f.gif)

**Comment by jakcpto** [comment]
Switched to 3.1.62 version on the not public analytics. 
Now waiting to rebuild the instance.
After that I'll check.
