### ISSUE TITLE
minor filter glitch: checkbox All keeps on while one other filter element is on too

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#297]
<img width="260" alt="Screenshot 2022-11-20 at 4 21 37 PM" src="https://user-images.githubusercontent.com/2781759/202910477-c76f382d-1575-48c5-85e2-5b9ca39e23b3.png">

**Comment by gnibeda** [comment]
Fixed in 3.1.55

**Comment by evshvarov** [comment]
Filters do not work at all now
<img width="374" alt="Screenshot 2023-01-16 at 11 20 44 AM" src="https://user-images.githubusercontent.com/2781759/212619913-78675db0-92b5-4a3e-aec5-0b93b7e9a1e7.png">
