### ISSUE TITLE
license problem (IRIS, Docker) - TESTS!!

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#306]
Error: Invalid Community Edition license, may have exceeded core limit. - Shutting down the system : $zu(56,2)= 0Starting IRIS

https://github.com/intersystems-community/DeepSeeWeb/actions/runs/3674512494/jobs/6212816395

![Image](https://user-images.githubusercontent.com/77621970/207288170-b31242c6-5bf6-48da-8af1-3fc1c1238624.png)

**Comment by jakcpto** [comment]
Every year the issue like that occurs.
In the irishealth-community:2021.1.0.215.3-zpm image the license is outdated.

Everyone who use this image should switch to use next version of IRIS.

**Comment by jakcpto** [comment]
Lets use say "2022.2.0.368.0-zpm" version.
Seems to be good.

**Comment by jakcpto** [comment]
Solution https://github.com/intersystems-community/DeepSeeWeb/pull/307
