### ISSUE TITLE
Support valuelist/displaylist properties for choose controls

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#308]
Choosedatasorce, chooserowspec,choosecolspec besides termlist can also be setup with valuelist and displaylist.

**Comment by evshvarov** [comment]
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Bug/ChooseDataSource.dashboard)

**Comment by Lena-Ev** [comment]
Check if back end works here - if these values are sent to DSW-?

**Comment by Frisle** [comment]
I am appointed to look for the data.

So, if i am understand it correctly this is the data required.

{
                    "action": "chooseDataSource",
                    "activeWhen": "",
                    "controlClass": "",
                    "displayList": "Patients by Color,Patients by Group",
                    "label": "Data",
                    "location": "widget",
                    "name": "",
                    "readOnly": 0,
                    "size": "",
                    "source": "Widget1",
                    "target": "Widget1",
                    "targetProperty": "",
                    "targetPropertyDisplay": "",
                    "text": "",
                    "timeout": "",
                    "title": "",
                    "type": "auto",
                    "value": "",
                    "valueList": "Use in Dashboards/Patients by Favorite Color.pivot,Use in Dashboards/Patients by Group.pivot",
                    "valueRequired": 0
                }

According to this data set, displayList and valueList is sended correctly and in full volume

**Comment by evshvarov** [comment]
great! thank you, Dmitry!
let’s transfer the task to @gnibeda

**Comment by gnibeda** [comment]
Done in 3.1.54
