### ISSUE TITLE
Change in the link  &-> %26 when go to Zen

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#310]
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/Demo%20Filter%20Interoperability.dashboard

Should be:
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20%26%20Plugins/Demo%20Filter%20Interoperability.dashboard

**Comment by gnibeda** [comment]
Done in 3.1.54
