### ISSUE TITLE
Returned path for tuples is incorrect

### ISSUE THREAD

**Issue by gnibeda** [intersystems-community/DeepSeeWeb#312]
In the last version of mdx2json returned path of tuples is incorrect:
Request: `/MDX2JSON/MDX?Namespace=IRISAPP`
Payload: `{"MDX":"SELECT NON EMPTY [Measures].[Amount Sold] ON 0,NON EMPTY [DateOfSale].[Actual].[YearSold].Members ON 1 FROM [HOLEFOODS]"}`

**Actual result:**
![image](https://user-images.githubusercontent.com/9804674/209407567-7db135e7-a9cd-4270-9d0c-4b463047671d.png)
**Expected result:**
path shouldn't contain brackets, eg. `path: "[DateOfSale].[Actual].[YearSold].&[2017]"`

Can be tested here: https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/irisapp/Widget%20Examples/All%20Charts.dashboard

**Comment by jakcpto** [comment]
Ok, got it.

**Comment by Lena-Ev** [comment]
For the second drill something dosent work

**Comment by evshvarov** [comment]
Fixed in 3.1.53
