### ISSUE TITLE
funny artifacts on pies

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#318]
<img width="726" alt="Screenshot 2023-01-16 at 11 11 40 AM" src="https://user-images.githubusercontent.com/2781759/212618589-602eb5d7-6c1b-4e25-b279-d511695697fa.png">

**Comment by Lena-Ev** [comment]
@evshvarov could you please provide an example or how to reproduce

**Comment by evshvarov** [comment]
Just click left-to-right buttons on decoration and back and you'll see it

**Comment by evshvarov** [comment]
[It is here](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/irisapp/Bug/SeveralPies.dashboard)
the [video](https://www.loom.com/share/0a81ceb49169461c90b6be3d9c70fc5f)

**Comment by Lena-Ev** [comment]
Switch on and then off annotations and then values

**Comment by gnibeda** [comment]
Done in 3.1.79
