### ISSUE TITLE
Let Drill through to limit the output upon the category in Graph widgets

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#320]
Currently drillthrough show everything.
But it should limit the output upon the slice.
E.g. [here](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Basic%20Dashboard%20Demo.dashboard):
if click on 60+ male it should show only those records.
Currently it shows males and females:
<img width="1168" alt="Screenshot 2023-01-17 at 3 57 30 PM" src="https://user-images.githubusercontent.com/2781759/212893306-7be5974e-001c-49f7-b0b6-aa468a7a23c4.png">

**Comment by gnibeda** [comment]
Done in 3.1.57

**Comment by evshvarov** [comment]
Works!
