### ISSUE TITLE
Drill through implementation

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#321]
https://github.com/intersystems-community/DeepSeeWeb/issues/272#issuecomment-1368260673

But drillthrough doesn't work after first drilldown.
Video:

https://www.loom.com/share/2a757ba2eeea4e6b97422d26aaad1ae6
and [example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Pareto%20Charts/Pareto%20Chart%20for%20Category.dashboard) @gnibeda

**Comment by gnibeda** [comment]
Dashboard: 
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/irisapp/Pareto%20Charts/Pareto%20Chart%20for%20Product%20and%20Category.dashboard

second widget mdx:
```
WITH  MEMBER [MEASURES].[Revenue as Percent of Total] AS 'Measures.[Amount Sold] / %MDX(\"select Measures.[Amount sold]on 1 from holefoods\",\"%CONTEXT\",\"filters|columns\")',FORMAT_STRING='##.##%;;;;' MEMBER [MEASURES].[Revenue Percent Cumulative] AS 'Measures.[Revenue as Percent of Total] + %CELL(0,-1)',FORMAT_STRING='##.##%;;;;' SELECT {[Measures].[Amount Sold],[MEASURES].[REVENUE PERCENT CUMULATIVE]} ON 0,NON EMPTY ORDER([Product].[P1].[Product Category].Members,Measures.[Amount Sold],BDESC) ON 1 FROM [HOLEFOODS]
```

DSW simply adds filters to it for drilltrhough(`%FILTER [Product].[P1].[Product Category].&[Seafood] %FILTER [Product].[P1].[Product Name].&[SKU-601]`):
```
DRILLTHROUGH  WITH  MEMBER [MEASURES].[Revenue as Percent of Total] AS 'Measures.[Amount Sold] / %MDX(\"select from holefoods\",\"%CONTEXT\",\"filters|columns\")',FORMAT_STRING='##.##%;;;;' MEMBER [MEASURES].[Revenue Percent Cumulative] AS 'Measures.[Revenue as Percent of Total] + %CELL(0,-1)',FORMAT_STRING='##.##%;;;;' SELECT {[Measures].[Amount Sold],[MEASURES].[REVENUE PERCENT CUMULATIVE]} ON 0,NON EMPTY ORDER([Product].[P1].[Product Name].&[SKU-601].children,Measures.[Amount Sold],BDESC) ON 1 FROM [HOLEFOODS] %FILTER [Product].[P1].[Product Category].&[Seafood] %FILTER [Product].[P1].[Product Name].&[SKU-601]
```

Response from mdx2json is empty. Please check.

**Comment by Lena-Ev** [comment]
Send working example

**Comment by Frisle** [comment]
Working example

"DRILLTHROUGH  WITH  MEMBER [MEASURES].[Revenue as Percent of Total] AS 'Measures.[Amount Sold] / %MDX(\"select from holefoods\",\"%CONTEXT\",\"filters|columns\")',FORMAT_STRING='##.##%;;;;' MEMBER [MEASURES].[Revenue Percent Cumulative] AS 'Measures.[Revenue as Percent of Total] + %CELL(0,-1)',FORMAT_STRING='##.##%;;;;' SELECT {[Measures].[Amount Sold],[MEASURES].[REVENUE PERCENT CUMULATIVE]} ON 0,NON EMPTY ORDER([Product].[P1].[Product Category].&[Seafood].children,Measures.[Amount Sold],BDESC) ON 1 FROM [HOLEFOODS] %FILTER [Product].[P1].[Product Name].&[SKU-601]"

**Comment by jakcpto** [comment]
@gnibeda take a look at working MDX above.
The difference is in ORDER statement.

May DSW change the ORDER in MDX?

**Comment by gnibeda** [comment]
Done in 3.1.65

**Comment by evshvarov** [comment]
It works!
