### ISSUE TITLE
Show only meters that are determined in a widget

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#324]
Shows 3 meters:
<img width="462" alt="Screenshot 2023-01-24 at 3 01 54 PM" src="https://user-images.githubusercontent.com/2781759/214275134-f1067447-714c-4f8e-a9ce-8b7109b1da5f.png">

But should be only one:
<img width="366" alt="Screenshot 2023-01-24 at 3 02 29 PM" src="https://user-images.githubusercontent.com/2781759/214275239-551b882e-2b8b-4cf7-8291-58255491b345.png">

DSW need to display meters, that are listed in Meters section of the widget:
<img width="326" alt="Screenshot 2023-01-24 at 3 03 51 PM" src="https://user-images.githubusercontent.com/2781759/214275568-564f7e62-2e11-4d4a-bc0b-765a6d4b5575.png">

[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Widget%20Examples/Meters%20B.dashboard)

**Comment by gnibeda** [comment]
FE needs meters settings in `/MDX2JSON/Dashboard` request. Or you can make it so `/MDX2JSON/MDX` returns only selected meters. up to you

**Comment by jakcpto** [comment]
The `/MDX2JSON/Dashboard` request returns "dataProperties" section with necessary data.
Each meter has own dataset like in example attached, with "dataValue" as a name of Data fields from MDX.

Look at "dataValue":"Avg Test Score"

`..."basemdx":"SELECT {[Measures].[%COUNT],[Measures].[Avg Test Score],[MEASURES].[UNIQUE DOCTOR COUNT]} ON 0 FROM [PATIENTS]",
			"controls":[
			],
			"cube":"Patients",
			"dataProperties":[ {
					"align":"",
					"baseValue":"",
					"dataValue":"Avg Test Score",
					"display":"value",
					"format":"#.##",
					"label":"Avg Test Score",
					"name":"",
					"override":"",
					"rangeLower":50,
					"rangeUpper":100,
					"showAs":"value",
					"style":"",
					"subtype":"",
					"summary":"",
					"summaryValue":"",
					"targetValue":"",
					"thresholdLower":50,
					"thresholdUpper":100,
					"valueColumn":0,
					"width":""
				}
			],
			"dataSource":"Use in Dashboards\/For Meter Demos.pivot",
			"displayInfo": {
				"colWidth":1,...`

In next example I've added the second meter to the widget, and now I have two arrays:
![image](https://user-images.githubusercontent.com/41373877/214499734-540a1413-fb0c-4222-9774-e0ce55ba6db1.png)

**Comment by jakcpto** [comment]
@gnibeda I think DSW should read this property and display only dataValue meters.

**Comment by gnibeda** [comment]
This is additional data for data properties, it can be empty if no options are set.
So using it to determine visibility for meter will cause empty meters on widgets without options.

**Comment by evshvarov** [comment]
So if this data is not empty rely on it.

**Comment by gnibeda** [comment]
@evshvarov, so if the user customized only one meter, and others leave with default settings, he will see only one meter? is this expected?
Also, all meters on existing dashboards will be not visible if there are no custom settings for them, but one(or more) have custom settings

**Comment by evshvarov** [comment]
Yes, if only one is customized, show only this one.

**Comment by evshvarov** [comment]
Why do you spread the behavior of one widget on all the widgets on a
dashboard?

**Comment by evshvarov** [comment]
OK, we can simplify this: let's just show only customized meters. If there
are no customized, don't show any.

**Comment by gnibeda** [comment]
Done in 3.1.65

**Comment by evshvarov** [comment]
It works!

**Comment by evshvarov** [comment]
In this case (cannot give online example) it shows 2 meters, but there are 5 setup:
<img width="1407" alt="Screenshot 2023-02-11 at 11 09 03 PM" src="https://user-images.githubusercontent.com/2781759/218265958-bc77a148-b2b6-4712-80b5-a244f0cb1859.png">

**Comment by gnibeda** [comment]
Please check that mdx2json returns data for all 5 meters. Check `tuples` in `cols` in `/mdx` response

**Comment by evshvarov** [comment]
Please fix also speedometers: should be one, not 3:
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Widget%20Examples/Meters%20B.dashboard
Same logic

**Comment by evshvarov** [comment]
also @jakcpto  - please check if the array of meters is being delivered from MDX2JSON. It looks like we should deliver this one too, not only data properties

**Comment by evshvarov** [comment]
@jakcpto @Frisle - please check, that Meters array comes from MDX2JSON. It looks like they can be different with Data Properties. Anyway, now as @gnibeda says there is not enough info in data-properties, that's why we don't see meters in clients' dashboards.

**Comment by Frisle** [comment]
@evshvarov i found the problem and fix it for this widgets
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Widget%20Examples/Meters%20B.dashboard

But i do not have any other widgets examples to test it so i am not sure this hack will work for any other text meter

![Postman_zUlDNk7hJj](https://user-images.githubusercontent.com/47441164/218981954-3dc1dc78-dc61-4009-8f50-d9f96c78c3b6.png)

The dimension property is now displayed

**Comment by evshvarov** [comment]
Great! can you make a PR?

**Comment by Frisle** [comment]
Yes already sent

**Comment by Lena-Ev** [comment]
new issue is opened
