### ISSUE TITLE
Some filters in Sales Against Targets does not work

### ISSUE THREAD

**Issue by Frisle** [intersystems-community/DeepSeeWeb#332]
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/Sales%20Against%20Targets.dashboard

![chrome_ch5gqRVknc](https://user-images.githubusercontent.com/47441164/216904692-64a517df-2f2e-488c-a907-2364b0decaea.gif)

While product filters send this:

![chrome_GtVvLULVJP](https://user-images.githubusercontent.com/47441164/216905756-e11182ef-2ba1-4ce3-b8bf-334d0bdc3432.png)

Looks like the problem in the frontend

**Comment by evshvarov** [comment]
It's not a DSW issue
