### ISSUE TITLE
Filter field does not show

### ISSUE THREAD

**Issue by Frisle** [intersystems-community/DeepSeeWeb#333]
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Pivot%20Variables/Commission%20Calculator.dashboard

The problem is with the filter destination. When place "Widget" filter is empty:

![chrome_9bpX5KpYQJ](https://user-images.githubusercontent.com/47441164/216911711-5d92f63b-a3e2-4aaa-8a82-40ae79e835c1.png)

When placing the filter on the "Dashboard", everything works:
![chrome_yKJobSwSy0](https://user-images.githubusercontent.com/47441164/216912743-d81c080c-97bb-4cf6-afcb-da27471af914.png)

**Comment by gnibeda** [comment]
Request `/MDX2JSON/Dashboard?Namespace=IRISAPP` returns empty filters array: `filters: []`

**Comment by evshvarov** [comment]
Works now.
