### ISSUE TITLE
KPI Listing doesn't work

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#334]
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/KPIs%20&%20Plugins/KPI%20with%20Listing.dashboard

**Comment by Lena-Ev** [comment]
Request needed which will allow to make request for KPI drillthrough

**Comment by Lena-Ev** [comment]
duplicates #291
