### ISSUE TITLE
actions do not work KPI

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#336]
E.g. add patients - it should call a method on IRIS to add some patients. It works in DSZ
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Real%20Time%20Updates.dashboard

**Comment by Lena-Ev** [comment]
method is called:
https://pie-chart-bug.demo.community.intersystems.com/MDX2JSON/Action/DemoDataChanges.kpi/AddPatients?Namespace=IRISAPP

![Image](https://user-images.githubusercontent.com/77621970/217236774-6a2f8540-9b5f-4dac-887f-a4785fdc9f08.png)

**Comment by jakcpto** [comment]
When last PR will be merged, this issue will be solved.

**Comment by evshvarov** [comment]
Works! With MDX2JSON 3.2.11. Thanks!
