### ISSUE TITLE
create class with Data in MDX2JSON to change dates filter for calendar

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#337]
Class Date Picker

**Comment by Frisle** [comment]
Is this what is required?

![chrome_zHLsBdFH6C](https://user-images.githubusercontent.com/47441164/218636713-66423159-1b70-4ae7-8b76-49a554018f28.png)

DSW does not have realisation for that kind control of right now

![chrome_x7jvMBWJoK](https://user-images.githubusercontent.com/47441164/218637447-0de01ab3-5e5b-45ce-b992-0297ae7e4e6f.png)

Or calendar widgwet with date pick is required?

**Comment by jakcpto** [comment]
Lets use "%ZEN.Component.calendar"
Response in /Dashboard will be like 

```
{action: "applyFilter", activeWhen: "", controlClass: "%ZEN.Component.calendar", displayList: "",…}
...
controlClass : "%ZEN.Component.calendar"
...
```

It's a bad example, but on https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/KPIs%20&%20Plugins/Demo%20Filter%20Interoperability.dashboard used this type of control.

in Zen looks like 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/41373877/220057333-856ae1ad-9203-4c5e-880b-5cd5d4d961c2.png">
