### ISSUE TITLE
UX: If Filter is situated low or if i it is long it is impossible to accept the value

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#341]
<img width="1412" alt="Screenshot 2023-02-12 at 1 13 07 AM" src="https://user-images.githubusercontent.com/2781759/218271434-6df6f27a-6968-4f64-9c9b-77d8783d2ccd.png">

**Comment by evshvarov** [comment]
Or if there are a lot of elements in the filter

**Comment by Lena-Ev** [comment]
bug - filter should open to the up
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/77621970/218723048-981453ce-d143-4009-95a9-5ef91031a88a.png">

**Comment by evshvarov** [comment]
This solved the problem "for now". Thank you
