### ISSUE TITLE
Meters: Use format in Data Properties

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#344]
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Bug/KPI%20with%20Meters.dashboard)

**Comment by Lena-Ev** [comment]
format doesn't come beacuse of the KPI
add fromat to properties

**Comment by Frisle** [comment]
Made a PR with a fix. We previously discussed this decision with @gnibeda and came to an agreement on it. The format is now in the Widget section
![Postman_DySjIQlDLs](https://user-images.githubusercontent.com/47441164/220536399-002a7e22-2eb9-49a0-828c-2438c0be0cd7.png)

**Comment by gnibeda** [comment]
Just note, that I suggested placing it inside `dataProperties`, as it was before.

**Comment by Frisle** [comment]
Clearly, data properties are preferred. But during development, I ran into an untraceable bug that was losing this parameter on the path to the data properties, so I decided to put it somewhere where it is not lost. Now the "format" is only there for KPIs.

**Comment by evshvarov** [comment]
Fixed in 3.1.68

**Comment by evshvarov** [comment]
if there are several data properties with different format this causes problems. 
E.g.: 
<img width="1477" alt="Screenshot 2023-02-24 at 5 16 15 PM" src="https://user-images.githubusercontent.com/2781759/221187884-3daaadff-6046-48be-8a05-b0a475bf1e83.png">

**Comment by Frisle** [comment]
Here is the solution. Now format appearing in dataProperties
https://github.com/intersystems-ru/Cache-MDX2JSON/pull/97

**Comment by Frisle** [comment]
@evshvarov can you take a look? Format for multiple text meters should be fixed by now.

**Comment by evshvarov** [comment]
Yes, this is fixed with MDX2JSON 3.2.18
<img width="1452" alt="Screenshot 2023-02-27 at 10 22 30 PM" src="https://user-images.githubusercontent.com/2781759/221650341-70a05103-540e-43ee-9b1a-8c83511b0441.png">
