### ISSUE TITLE
If MDX contains HEAD don't add another HEAD for RowCount implementation

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#345]
Update it. in this case

**Comment by evshvarov** [comment]
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Bug/RowCount.dashboard)

**Comment by Lena-Ev** [comment]
where is th Format?
Add format to data properties (better)

**Comment by evshvarov** [comment]
Fixed! Works in 3.1.68
