### ISSUE TITLE
[urgent] Add support of Sum% option in Scorecards

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#350]
Add support Sum% for scorecards.
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/KPIs%20&%20Plugins/SQL%20Based%20KPI.dashboard).

**Comment by Frisle** [comment]
@gnibeda can you take a look?
The data is received as "overrides". The backend sends it as expected. Should it be received in dataProperties? Widgets by themselves do not have these properties.

![Screenshot 2023-02-27 123715](https://user-images.githubusercontent.com/47441164/221492096-e0513a37-d0be-477a-b065-78e1f1c2e087.png)

**Comment by Lena-Ev** [comment]
after implementation on the FE -> start implementation on BE

**Comment by gnibeda** [comment]
Done in 3.1.70

**Comment by evshvarov** [comment]
Cannot check as dashboard STOPPED loading :)
<img width="1102" alt="Screenshot 2023-03-06 at 12 36 29 PM" src="https://user-images.githubusercontent.com/2781759/223058595-2324a951-3a33-485b-b95f-29e909a0ea6b.png">

**Comment by jakcpto** [comment]
@evshvarov can you please add screenshots of Developer Tools, Network

**Comment by evshvarov** [comment]
Still issue in 3.1.71

**Comment by evshvarov** [comment]
Solved in 3.1.73
