### ISSUE TITLE
Fix Speedometer widget

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#351]
Should be the same amounts as data properties defined.
should show proper values.
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Widget%20Examples/Meters%20B.dashboard)

**Comment by gnibeda** [comment]
As discussed, now `data properties` will affect all widgets if defined.

**Comment by evshvarov** [comment]
Works in 3.1.70
