### ISSUE TITLE
Use format from Data properties in meters

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#352]
sometimes format is not used.
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Bug/Meter%20Pivot%20DataProperties%20format.dashboard)

**Comment by Lena-Ev** [comment]
priority to DataProperrties - change to that everywhere but tables

**Comment by gnibeda** [comment]
Done in 3.1.70

**Comment by evshvarov** [comment]
Fixed
