### ISSUE TITLE
Some issues with Scorecard plot type

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#353]
Should be:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2781759/221652002-eced66ce-e65f-4898-9b03-6ae517e245fb.png)

But now:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2781759/221651960-7890b607-f791-40aa-9a47-a61dfc258b50.png)

Formatting for col data and plot problems

**Comment by Lena-Ev** [comment]
check show as example

**Comment by Lena-Ev** [comment]
format we ith %  - means multiply by 100 and put  % in the beginning of the number

%## means:
0.1 -> %10

![Image](https://user-images.githubusercontent.com/77621970/221849626-b0abfc32-b271-48f3-96c1-57140eadb313.png)

**Comment by evshvarov** [comment]
[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Widget%20Examples/Scorecard%20with%20Plot%20Boxes.dashboard)

**Comment by gnibeda** [comment]
Done in 3.1.70

**Comment by evshvarov** [comment]
Solved in 3.1.71
