### ISSUE TITLE
Strange data visualisation in line chart

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#354]
<img width="1477" alt="Screenshot 2023-02-27 at 10 39 02 PM" src="https://user-images.githubusercontent.com/2781759/221653553-a0c7230d-d23a-4998-b055-2c455b0e34ed.png">

**Comment by Lena-Ev** [comment]
for chart show only that ones which have data properties, ones without data properties - do not show at all

**Comment by gnibeda** [comment]
Done in 3.1.70

**Comment by evshvarov** [comment]
still in place

**Comment by evshvarov** [comment]
still doesn't work in 3.1.71

**Comment by evshvarov** [comment]
Fixed in 3.1.74
