### ISSUE TITLE
Combo Chart doesn't work

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#357]
Should be 
<img width="1120" alt="Screenshot 2023-03-04 at 10 50 44 AM" src="https://user-images.githubusercontent.com/2781759/222880756-84f6572c-7891-47e9-87d8-597ddc86c142.png">
But
<img width="1431" alt="Screenshot 2023-03-04 at 10 50 56 AM" src="https://user-images.githubusercontent.com/2781759/222880762-139b90e3-d1e1-4206-a438-6deb65d34c29.png">

[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Widget%20Examples/Combo%20Chart.dashboard)

**Comment by Lena-Ev** [comment]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/77621970/223409213-245c9207-b683-406e-997f-943c3214a17c.png">

**Comment by Lena-Ev** [comment]
where is serias type is taken from?

**Comment by Frisle** [comment]
seriesTypes":"area,line" comes from here and is written to the override properties
![chrome_b0Yeu0e6r9](https://user-images.githubusercontent.com/47441164/224225236-93233fb6-337c-4f19-aed2-80d2130b931a.gif)

**Comment by evshvarov** [comment]
Works
