### ISSUE TITLE
Speedometer value is different from DSZ

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#358]
Should be:
<img width="397" alt="Screenshot 2023-03-04 at 10 54 39 AM" src="https://user-images.githubusercontent.com/2781759/222880925-38c5ee82-ffc7-4e2c-bd1a-93a96d68d7a6.png">

But:
<img width="502" alt="Screenshot 2023-03-04 at 10 54 48 AM" src="https://user-images.githubusercontent.com/2781759/222880929-35b1e426-0aa4-4841-8240-4e40744f4078.png">

**Comment by Lena-Ev** [comment]
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Widget%20Examples/Meters%20B.dashboard

**Comment by evshvarov** [comment]
Fixed in dsw 3.1.71
