### ISSUE TITLE
Some of the text meters are not show data

### ISSUE THREAD

**Issue by Frisle** [intersystems-community/DeepSeeWeb#360]
There was a problem with a text meter containing one specific measure "Delta".

All data has been received, but the data is not visible. Although ZEN displays data very well.
The text meter on the left is displayed as expected with the same configuration.

![Screenshot 2023-03-15 115425](https://user-images.githubusercontent.com/47441164/225220092-4c248aac-b2f8-4f2b-a217-1d5fa1fe7961.png)
![Screenshot 2023-03-15 115556](https://user-images.githubusercontent.com/47441164/225220111-110bddad-0793-49b0-a39a-05170bae39ba.png)

@gnibeda can you please take a look? Is right data coming to front-end?
https://analytics.openexchange.intersystems.com/dsw/index.html#/ANALYTICS/OEX.dashboard

**Comment by evshvarov** [comment]
Delta is a special key-word for DeepSeeWeb.
If it is presented in dataset DSW shows it as delta (+/-) to a previous
parameter in a row.
Did show it in the past at least )

**Comment by Frisle** [comment]
@evshvarov I thought of Delta as a reserved keyword used by the front end and renamed it to DeltaCount but no luck. Then I give it a name without the word "delta" and it works. Thank you. This is the fastest closed task I have ever seen.

**Comment by evshvarov** [comment]
Yes, as there could be Delta1, Delta2 etc in one dataset.
