### ISSUE TITLE
Column Scroll in Drillthrough doesn't work

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#366]
If there are more columns in drill-through table than width allows to display it's not possible to scroll right to see all of them

[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Bug/ChooseDataSource.dashboard)

**Comment by evshvarov** [comment]
The cols scrolling right-left worked before

**Comment by gnibeda** [comment]
Done in 3.1.87
