### ISSUE TITLE
Remember "Exclude" clause in filters

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#367]
If "Exclude" clause is chosen for some filter elements it is not shown for the second turn of editing

[Example](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Pareto%20Charts/Pareto%20Chart%20for%20Category.dashboard)

<img width="738" alt="Screenshot 2023-04-28 at 12 36 37 PM" src="https://user-images.githubusercontent.com/2781759/235099075-45eaa024-8ef1-4e33-9f54-751d6aadb2fb.png">

**Comment by gnibeda** [comment]
Done in 3.1.87
