### ISSUE TITLE
Filter to the filtered widgets + tooltip

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#369]

**Comment by gnibeda** [comment]
Done in 3.1.88

**Comment by evshvarov** [comment]
<img width="510" alt="Screenshot 2023-05-08 at 5 24 41 PM" src="https://user-images.githubusercontent.com/2781759/236835930-2c59a415-94be-48c8-8166-3f592a555e11.png">
Very cool!
