### ISSUE TITLE
Ignores ns parameter in the URL

### ISSUE THREAD

**Issue by daimor** [intersystems-community/DeepSeeWeb#37]
When I open DSW for embedding to my application, I'm using URL like this `/dsw/index.html#!/d/Dashboard%20with%20Meters.dashboard?ns=ENSDEMO&embed=1&lang=cs`. But it fails to open, due to some requests to MDX2JSON asking for SAMPLES namespace, which I don't have.

**Comment by eduard93** [comment]
Still relevant as of 2.1.32 (install via ZPM)
![image](https://user-images.githubusercontent.com/5127457/61592416-9fe0ad00-abdb-11e9-9dce-185b97695ed4.png)
