### ISSUE TITLE
There is an issue with Data Driven Colors dash

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#371]
[Example](https://pie-chart-bug.demo.community.intersystems.com/csp/user/_DeepSee.UserPortal.DashboardViewer.zen?DASHBOARD=Data%20Driven%20Colors.dashboard)

**Comment by evshvarov** [comment]
yes

**Comment by Frisle** [comment]
Fixed https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Data%20Driven%20Colors.dashboard

**Comment by evshvarov** [comment]
If the issue was in dashboards? or where?

**Comment by Frisle** [comment]
The request to the data source did not match the source name. I changed the name of the data source

**Comment by evshvarov** [comment]
ok!

**Comment by evshvarov** [comment]
In a repo?

**Comment by Frisle** [comment]
A PR? I have made one yes
