### ISSUE TITLE
Drilldown works unstable

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#375]
[Example](https://samples-bi-demo.demo.community.intersystems.com/dsw/index.html#/USER/Patients%20Compound%20Cube.dashboard)

Please try to drilldown on the widget with years (top right)

**Comment by Lena-Ev** [comment]
check backend

**Comment by Frisle** [comment]
Drilldown doesn`t work when ResultSet trying to get Axis from this MDX 

"SELECT {[Measures].[Patient Count],[Measures].[Doctor Count],[Measures].[Avg Monthly Rainfall Inches]} ON 0,NON EMPTY [BirthD].[H1].[Decade].&[1950s].children ON 1 FROM [COMPOUNDCUBE/COMPOUNDCUBE] %FILTER [BirthD].[H1].[Decade].&[1950s]"

QueryKey received by ResultSet doesn't have colKey, then ResultSet cannot get Axis related to the MDX and therefore data related to it. 

If MDX sent like this

"SELECT {[Measures].[Patient Count],[Measures].[Doctor Count],[Measures].[Avg Monthly Rainfall Inches]} ON 0,NON EMPTY [BirthD].[H1].[Decade].&[1950s].children ON 1 FROM [COMPOUNDCUBE/COMPOUNDCUBE]"

Received QueryKey have link to Axis and data is acquired

I suggest changing the MDX sent by the frontend

**Comment by Frisle** [comment]
I guess this issue is directly related to this one  https://github.com/intersystems-community/DeepSeeWeb/issues/377

**Comment by Lena-Ev** [comment]
try rest API to resolve
