### ISSUE TITLE
Maybe let's remove scrollbars in pivots?

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#378]
But keep the scrolling functionality?
See how it is being displayed:
<img width="1486" alt="Screenshot 2023-05-09 at 11 14 08 PM" src="https://github.com/intersystems-community/DeepSeeWeb/assets/2781759/ce00ebb5-2ee9-4279-a4af-95f0c38d39b8">

[Example](https://samples-bi-demo.demo.community.intersystems.com/dsw/index.html#/USER/KPIs%20&%20Plugins/Demo%20Filter%20Interoperability.dashboard)

**Comment by gnibeda** [comment]
This is how the pivot table works. I can remove the horizontal scroll completely or leave it as it is.
Or I can write a new pivot table. The old one was coded when there is no possibility for freezing columns and rows via css, no resize observer exists, etc.. so it was mad with some workarounds.

**Comment by evshvarov** [comment]
OK
