### ISSUE TITLE
Filter panel too small and doesn't show all the filters

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#386]
fixed 3.1.97

**Comment by Lena-Ev** [comment]
@evshvarov check and close issue please

**Comment by gnibeda** [comment]
Before testing, please reset app settings from the menu:
![image](https://github.com/intersystems-community/DeepSeeWeb/assets/9804674/1f2146d6-f480-44d9-b635-91d53f751318)
