### ISSUE TITLE
Some default filter values are not supported

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#387]

**Comment by evshvarov** [comment]
Example of the filter: "text":"Aug-2018+ Sep-2018+ Oct-2018+ Nov-2018+ Dec-2018+ Jan-2019+ Feb-2019+ Mar-2019",

**Comment by Lena-Ev** [comment]
@gnibeda needed

**Comment by gnibeda** [comment]
Please provide a link to a widget with such filters.

**Comment by evshvarov** [comment]
Works
