### ISSUE TITLE
Related filters. - don't work in DSW

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#388]

**Comment by Lena-Ev** [comment]
example

**Comment by Frisle** [comment]
@gnibeda the related filters is a default feature in ZEN it does not set manually. You just assign two filters and they work together. Here is the demonstration

This is how it works in ZEN
![chrome_M4HLWgIDC1](https://github.com/intersystems-community/DeepSeeWeb/assets/47441164/c6544fe5-a61d-4e3d-ad0c-44abf172482e)

And this is on DSW

![chrome_YJ6fwrMkIQ](https://github.com/intersystems-community/DeepSeeWeb/assets/47441164/e16f3ab8-109c-42a6-aab6-3cfc6242c712)

And here is the link to example 
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/test.dashboard

**Comment by Frisle** [comment]
We already have an endpoint for retrieving a filtered collection of filters. When we manually enter some data, the filter endpoint collects related filters.

Try to manualy input year value here 
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Pareto%20Charts/Pareto%20Chart%20for%20Category.dashboard

**Comment by gnibeda** [comment]
Done in 3.2.18

**Comment by Lena-Ev** [comment]
@evshvarov could you test this on your data?

**Comment by Frisle** [comment]
This is implemented and already working. The issue can be closed

![chrome_rFRudMZ1Z1](https://github.com/intersystems-community/DeepSeeWeb/assets/47441164/bee1e204-53e8-4f0a-a4ab-3ad87640c18a)

**Comment by evshvarov** [comment]
done
