### ISSUE TITLE
Need a parameter in URL to cancel any default filters

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#390]

**Comment by Lena-Ev** [comment]
check Filters =

**Comment by Frisle** [comment]
We discussed the issue with @gnibeda and came to the conclusion that this is a front-end task.

**Comment by gnibeda** [comment]
Done in 3.2.7

**Comment by Lena-Ev** [comment]
@evshvarov if works for you close the issue please
