### ISSUE TITLE
Encoded chars in URLs

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#393]
suppport links like
transformed by logi
https://appsight.iscinternal.com/dsw/index.html#/APPSIGHT/Downloads/Overview.dashboard?FILTERS%3DTARGET%3A*%3BFILTER%3A%5BTimeStamp%5D.%5BH2%5D.%5BMonthYear%5D.%26%5BNOW-1%5D%7E%5BProductMajorVersion%5D.%5BH1%5D.%5BProductMajorVersion%5D.%26%5B2022.1%5D

how it should be
https://appsight.iscinternal.com/dsw/index.html#/APPSIGHT/Downloads/Overview.dashboard?FILTERS=TARGET:*;FILTER:%5BTimeStamp%5D.%5BH2%5D.%5BMonthYear%5D.%26%5BNOW-1%5D~%5BProductMajorVersion%5D.%5BH1%5D.%5BProductMajorVersion%5D.%26%5B2022.1%5D

https://appsight.iscinternal.com/dsw/index.html#/APPSIGHT/Downloads/Overview.dashboard?FILTERS%3DTARGET%3A*%3BFILTER%3A%5BTimeStamp%5D.%5BH2%5D.%5BMonthYear%5D.%26%5BNOW%5D

this part should be readable by DSW -->
FILTERS%3DTARGET%3A*%3BFILTER%3A%5BTimeStamp%5D.%5BH2%5D.%5BMonthYear%5D.%26%5BNOW%5D 

https://appsight.iscinternal.com/dsw/index.html#/APPSIGHT/Downloads/Overview.dashboard?FILTERS=TARGET:*;FILTER:[TimeStamp].[H2].[MonthYear].&[NOW]~[ProductMajorVersion].[H1].[ProductMajorVersion].&[2022.1]

Logi transforms symbols
= -> %3D
: -> %3A
; -> %3B
~ -> %7E

so we need that DSW could transform them back or read this tranformed symbols like (%3D...)

**Comment by Lena-Ev** [comment]
check after release if it works

**Comment by Lena-Ev** [comment]
waiting for feedbacj from tecccode (double escaping)

**Comment by Lena-Ev** [comment]
@gnibeda release with crunch

**Comment by evshvarov** [comment]
my heart is here
