### ISSUE TITLE
Range filter has russian names for months

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#399]
<img width="702" alt="Screenshot 2023-08-26 at 2 41 52 PM" src="https://github.com/intersystems-community/DeepSeeWeb/assets/2781759/fbeffc6c-eb97-4eee-85af-afdf22067a23">
Even if browser is in English

**Comment by jakcpto** [comment]
Fixed by gnibeda

<img width="428" alt="image" src="https://github.com/intersystems-community/DeepSeeWeb/assets/41373877/311d0275-fd38-427c-a2a5-3903a7b7588d">
