### ISSUE TITLE
Please add the modes of 4-5-6 filters in a row

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#400]
3 rows is still too wide if I want to have a top bar of filters and use all the horisontal space for linecharts, barchats or other timeline related widgets:
<img width="1483" alt="Screenshot 2023-08-26 at 2 55 50 PM" src="https://github.com/intersystems-community/DeepSeeWeb/assets/2781759/ff7b6ccb-65fc-4c38-a3fe-d5de3ae9b6e7">

**Comment by Frisle** [comment]
This is implemented and working. The issue can be closed

**Comment by evshvarov** [comment]
done
