### ISSUE TITLE
Do not load widgets (pieChart, donutChart, treeMapChart) when using pivot variables

### ISSUE THREAD

**Issue by OlgaBorokhova** [intersystems-community/DeepSeeWeb#406]
Pivot example that doesn't load widgets
SELECT NON EMPTY %LABEL([Measures].[$variable.selectedMeasure],"Усього","") ON 0, NON EMPTY [crimeRegionD].[H1].[crimeRegionL].Members ON 1 FROM [CRIME]

But it works with pivot ($variable.selectedMeasure=crimeTotal)
SELECT NON EMPTY %LABEL([Measures].[crimeTotal],"Усього","") ON 0, NON EMPTY [crimeRegionD].[H1].[crimeRegionL].Members ON 1 FROM [CRIME]

The pivot variables are used for the project because there are 30 parameters for the map and diagram, which are substituted in this way to generate the data.

**Comment by Frisle** [comment]
The problem has been fixed. The solution was in the empty variable [MEASURES].[$variable.selectedMeasure]. Once the variable has been assigned a value, mdx is executed successfully.
