### ISSUE TITLE
Widget sharing links to base 64

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#408]
https://github.com/intersystems-community/analytics-dashboars/issues/270#issuecomment-1818472556

**Comment by SergeyCh94** [comment]
We are currently facing an issue with URL encoding in the DSW application. Problems arise when using Encode and Base64:

Link before encoding:
https://analytics.community.intersystems.com/dsw/index.html#/COMMUNITY/Monthly%20Reports/MembersPostsViews.dashboard?FILTERS%25253DTARGET:*;FILTER:%25255BDateDimension%25255D.%25255BH1%25255D.%25255BMonthYear%25255D.%252526%25255B202305%25255D:%252526%25255B202310%25255D%2526widget%253DMembers%3D%26FILTERS%3DVEFSR0VUOio7RklMVEVSOiU1QkRhdGVEaW1lbnNpb24lNUQuJTVCSDElNUQuJTVCTW9udGhZZWFyJTVELiUyNiU1QjIwMjMwNiU1RCUzQSUyNiU1Qk5PVyU1RA%3D%3D%26widget%3DPosts%20Table=&FILTERS=VEFSR0VUOio7RklMVEVSOiU1QkRhdGV

Link after Logi usage:
https://analytics.community.intersystems.com/dsw/index.html#/login?from=%2FCOMMUNITY%2FMonthly%2520Reports%2FMembersPostsViews.dashboard%3FFILTERS%252525253DTARGET:*;FILTER:%252525255BDateDimension%252525255D.%252525255BH1%252525255D.%252525255BMonthYear%252525255D.%2525252526%252525255B202305%252525255D:%2525252526%252525255B202310%252525255D%25252526widget%2525253DMembers%25253D%252526FILTERS%25253DVEFSR0VUOio7RklMVEVSOiU1QkRhdGVEaW1lbnNpb24lNUQuJTVCSDElNUQuJTVCTW9udGhZZWFyJTVELiUyNiU1QjIwMjMwNiU1RCUzQSUyNiU1Qk5PVyU1RA%25253D%25253D%252526wid%253D%2526FILTERS%253DVEFSR0VUOio7RklMVEVSOiU1QkRhdGVEaW1lbnNpb24lNUQuJTVCSDElNUQuJTVCTW9udGhZZWFyJTVELiUyNiU1QjIwMjMwNiU1RCUzQSUyNiU1Qk5PVyU1RA%253D%253D%2526widget%253DMembers%3D

These changes lead to the setting of a common filter on the dashboard. It has also been suggested to update the Base64 encoding to include the entire tail from the URL.

**Comment by gnibeda** [comment]
This is a known issue of Logi, It breaks valid URLs into invalid ones. I've added some support for invalid URLs, but Logi still can generate some crazy urls, that can't be processed. So I need to check each case separately.

Before I start checking it, please update DSW to the **last version(3.2.19)** - there are a lot of changes for Logi broken links support. Currently, you use a version that doesn't support broken links.

If after updating and regenerating the link by DSW and after it by Logi issue will stay - let me know.

**Comment by Lena-Ev** [comment]
@jakcpto @Frisle check please

**Comment by Frisle** [comment]
Links are now working as required. This issue is resolved
