### ISSUE TITLE
TreeMapChart does not fix legend

### ISSUE THREAD

**Issue by OlgaBorokhova** [intersystems-community/DeepSeeWeb#409]
Press button "Toggle legend" but refresh of the dasboard hide it.
![image](https://github.com/intersystems-community/DeepSeeWeb/assets/89194394/1695287b-20aa-4b4f-8a2c-82ab6f45af18)

Now version dsw  3.2.21
Compare with version 3.1.39 and it works well
![image](https://github.com/intersystems-community/DeepSeeWeb/assets/89194394/c8e86d3c-1699-4d3e-a4c0-a4ca3868592a)

**Comment by gnibeda** [comment]
fixed in 3.2.22
