### ISSUE TITLE
PieChart. Clicking on legend shows empty circle

### ISSUE THREAD

**Issue by OlgaBorokhova** [intersystems-community/DeepSeeWeb#410]
![image](https://github.com/intersystems-community/DeepSeeWeb/assets/89194394/d9d3355f-feb0-4078-8be9-3cb7b3b27eb0)
Now version dsw 3.2.21

Compare with version 3.1.39 and it works another way.
Clicking on legend item removes the sector from the diagram.
Before click
![image](https://github.com/intersystems-community/DeepSeeWeb/assets/89194394/796eea0b-bb18-4f40-9ab6-259b0db7416c)
After click
![clipboard-202312041314-9bfnt](https://github.com/intersystems-community/DeepSeeWeb/assets/89194394/fe16ce8e-e2f7-4e64-91df-161f7cf4b65f)

**Comment by gnibeda** [comment]
fixed in 3.2.22

**Comment by OlgaBorokhova** [comment]
Thanks. It works. The same problem with donutChart #413
