### ISSUE TITLE
BarChart. Drilldown does not work correctly

### ISSUE THREAD

**Issue by OlgaBorokhova** [intersystems-community/DeepSeeWeb#411]
We have embedded dsw widget into our application.
We have a combo box with Territory in the application. We apply this filter and drill down to the dsw widget.

The link with the filter and drill down looks like:
https://dev-erdr-map-web-7117.ipa.gpext.local/dsw/index.html#/MAP/map/Map.dashboard?&datasource=map%2FbarChart_2levels.pivot&FILTERS=TARGET:*;FILTER:%5BcrimeRegionD%5D.%5BH1%5D.%5BcrimeRegionL%5D.%2526%255B11%255D&variables=selectedMeasure.crimeRegistered~selectedPeriod.131&widget=barChart&noheader=1&disableContextMenu=1&autodrill=1&drilldown=%255BcrimeRegionD%255D.%255BH1%255D.%255BcrimeRegionL%255D.%2526%255B11%255D

Territory is the dictionary with 3 level hierarchy. 
Drill down to the 2nd and 3rd level using this link - works OK.
But the drill down from the 2nd level to the 3rd level using dsw widget drill-down standard functionality does not work correctly:
Click on any lines (text) except the first line on the diagram does not work at all.
If we click on the first line (text) widget refreshes but the drilldown does not happen for this line. But then, if we click on any line (text) we have a correct drill down.

Now version dsw 3.2.21

В приложении у нас есть комбобокс с фильтром Territory. Мы применяем этот фильтр и выполняем drilldown на виджете dsw.
Ссылка с фильтром видна выше.
Territory - это справочник с трехуровневой иерархией. 
Drilldown на 2-й и 3-й уровень по этой ссылке работает нормально.
Но, если выполнить переход на второй уровень через комбобокс, а затем переход со 2-го уровня на 3-й с помощью стандартной функциональности dsw widget drilldown, то работает некорректно:
Щелчок по любым линиям (тексту), кроме первой линии на диаграмме, не работает вообще.
Если мы нажмем на первую линию (текст), виджет обновится, но drilldown не произойдет для этой линии. А уже последующее нажатие на любую линию (текст) drilldown происходит корректно.

**Comment by gnibeda** [comment]
fixed in 3.2.22

**Comment by OlgaBorokhova** [comment]
Does it need any changes in application? 
Because it works without fixes now.

**Comment by gnibeda** [comment]
fixed in 3.2.23
