### ISSUE TITLE
A bug with crossjoins

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#417]
There is a setup where there is a crossjoin in one dimension and a set of measures.
DSW doesn't split data upon a crossjoin.
Here is an [example](https://samples-bi-demo.demo.community.intersystems.com/dsw/index.html#/USER/Bug/Crossjoin.dashboard)

**Comment by evshvarov** [comment]
<img width="833" alt="Screenshot 2024-03-20 at 1 20 22 PM" src="https://github.com/intersystems-community/DeepSeeWeb/assets/2781759/7039f0f5-b2ae-44a8-8046-a075aa6843e3">
<img width="870" alt="Screenshot 2024-03-20 at 1 20 09 PM" src="https://github.com/intersystems-community/DeepSeeWeb/assets/2781759/a871630a-7ba9-4a5e-aba9-26323172f1a7">

**Comment by gnibeda** [comment]
Found an issue on a FE side. Will fix it soon

**Comment by gnibeda** [comment]
fixed in 3.2.24
