### ISSUE TITLE
Adapt KPI listing to work on various plot types

### ISSUE THREAD

**Issue by Frisle** [intersystems-community/DeepSeeWeb#421]
Currently KPI listing is working only at pivot type (simple table) plot. Any other type is not supported yet 

GIF EXAMPLE

![chrome_2AgjO78XDI](https://github.com/intersystems-community/DeepSeeWeb/assets/47441164/91afbac4-fb16-4fa4-8c9d-ede8e1cff974)

Пример виджета с листингом

https://samples-bi-demo.demo.community.intersystems.com/dsw/index.html#/USER/KPIs%20&%20Plugins/KPI%20with%20Listing.dashboard

**Comment by Lena-Ev** [comment]
On click on the data:
<img width="350" alt="image" src="https://github.com/intersystems-community/DeepSeeWeb/assets/77621970/ef60a4f6-1629-4783-b68f-38f24a679fb0">

On click on the white part of widget:
<img width="261" alt="image" src="https://github.com/intersystems-community/DeepSeeWeb/assets/77621970/4c9dcddf-fbb6-470b-a233-19015a8921aa">

**Comment by Lena-Ev** [comment]
https://startup-dev.community.intersystems.com/dsw/index.html#/CSH/Startups/Startups.dashboard

**Comment by gnibeda** [comment]
fixed in 4.0.5

**Comment by Lena-Ev** [comment]
works? @Frisle

**Comment by Frisle** [comment]
@Lena-Ev yes, the drillthrough works correctly
