### ISSUE TITLE
Titles disappeared on tree-map

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#436]
Reproduced
https://got-analytics.demo.community.intersystems.com/dsw/index.html#/USER/Overview.dashboard
<img width="1034" alt="Screenshot 2024-07-17 at 3 24 04 PM" src="https://github.com/user-attachments/assets/3be0d909-501b-4dad-a13c-d7aff830d5a1">

**Comment by Lena-Ev** [comment]
@evshvarov done, test please on the new version 4.0.5

**Comment by evshvarov** [comment]
It works
