### ISSUE TITLE
Update LPT

### ISSUE THREAD

**Issue by ZitRos** [intersystems-community/DeepSeeWeb#47]
I've made some required fixes in LPT, please update to the [newest version](https://github.com/intersystems-ru/LightPivotTable/releases/tag/1.8.0).

Once updated, let Honza (skype:sacenhigh) know about the update.

Thanks!

**Comment by evshvarov** [comment]
In the new version the column with checkboxes in the listing mode is too wide:
(https://www.dropbox.com/s/gfefoh7d6q2upxl/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-03-03%2001.43.17.png?dl=0)

**Comment by ZitRos** [comment]
@evshvarov, I can't check your testcase (`{"data":{"Error":"ERROR #5001: Dashboard Basic Dashboard Demo.dashboard#/ does not exist"}`), but the newest version of LPT picks columns width from *.pivot if specified, or assigns `100px` width by default. Could you please check the *.pivot setting or make the test case available? Thanks!
Also, Anton @gnibeda and Evgeny, if [this option](https://github.com/intersystems-ru/LightPivotTable/blob/master/example/index.html#L134) is specified in DSW (I see it at least specified [here](http://146.185.143.59/dsw/index.html#!/d/test/PivotWidthTest.dashboard?ns=SAMPLES)), the column widths will try to fill all available space in widget to not to leave blank space there.

**Comment by ZitRos** [comment]
Talked to @evshvarov, it turned that this is LPT bug impacting listings.

**Comment by ZitRos** [comment]
Fixed, new version is [available](https://github.com/intersystems-ru/LightPivotTable/releases/tag/1.8.1). @evshvarov, regarding to hiding buttons, [there is an option](https://github.com/intersystems-ru/LightPivotTable/blob/65d6d9d9d9581cef06ad2c4c88b293e0f0e0f68d/example/index.html#L120) already. Thanks!

**Comment by evshvarov** [comment]
@ZitRos thank you so much!

**Comment by evshvarov** [comment]
@gnibeda would you please include it in the recent release and the [option](https://github.com/intersystems-ru/LightPivotTable/blob/65d6d9d9d9581cef06ad2c4c88b293e0f0e0f68d/example/index.html#L120) as well?  It hides the drill back button for LPT. It should be hidden for DSW forever.

**Comment by evshvarov** [comment]
@gnibeda can we close it?

**Comment by ZitRos** [comment]
@evshvarov DSW master [contains 1.8.0](https://github.com/intersystems-ru/DeepSeeWeb/blob/master/src/lib/lightPivotTable.js), the latest first-column width fix is still to come, but the things we've discussed here are done for 1.8.0.

**Comment by ZitRos** [comment]
LPT version [1.8.2](https://github.com/intersystems-ru/LightPivotTable/releases/tag/1.8.2) with alignment fix is on the road.
