### ISSUE TITLE
Allow axis scales to be linked or manually set

### ISSUE THREAD

**Issue by alexJaegerSTR** [intersystems-community/DeepSeeWeb#58]
Axis Scales should be allowed :

- To be set to a constant ranges (like in the default UserPortal)
- To be linked other charts so there can be two charts with identical scales.

**Comment by evshvarov** [comment]
It's the request for combochart - there is no way to setup axis and chart types

**Comment by Lena-Ev** [comment]
@alexJaegerSTR it works you can set up it in deep see zen in Y axis settings
