### ISSUE TITLE
Time Widget: Navigator view missing after time filter change

### ISSUE THREAD

**Issue by alexJaegerSTR** [intersystems-community/DeepSeeWeb#59]
After the time filter is changed the navigator view is missing.
![changed_timefilter](https://cloud.githubusercontent.com/assets/25840666/24458317/dc5632e6-1498-11e7-8883-bbc3d676d6d4.PNG)

**Comment by Lena-Ev** [comment]
fixed


![Image](https://user-images.githubusercontent.com/77621970/226130431-b95a8714-4ab1-4985-ba90-82e9edd6badc.png)
