### ISSUE TITLE
Shared filters don't meet the filter dropdown

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#92]
If you peek several items in filter and then share it you will get the working filter, but you cannot alter it, because drop down doesn't include the filtered items.

**Comment by Lena-Ev** [comment]
fixed, works
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/user/Widget%20Examples/Time%20Chart.dashboard?FILTERS=TARGET:*;FILTER:%5BOutlet%5D.%5BH1%5D.%5BCountry%5D.%26%5BFrance%5D
